### ISSUE TITLE
[discussion] about memory allocation wrappers

### ISSUE THREAD

**Issue by vtorri** [lexbor/lexbor#1]
some questions : 

1) Why did you add wrappers around memory management ?

2) why is the wrapper around free() returning a void * ? That seems strange

3) do you plan to use memory pools ?

4) have you considered the usage of jmalloc ?

**Comment by lexborisov** [comment]
1. They must be done inline functions. Allow the user to implement them as they want. 
2. Syntactic sugar. `lexbor_free` always returns `NULL`. For this:
```C
if (object->table != NULL) {
	object->table = lexbor_free(object->table);
}
```
not so
```C
if (object->table != NULL) {
	lexbor_free(object->table);
	object->table = NULL;
}
```
3. I use them. I allocate pieces of memory, split them, caching and so on. See [mraw](https://github.com/lexborisov/lexbor/blob/master/source/lexbor/core/mraw.c), [mem](https://github.com/lexborisov/lexbor/blob/master/source/lexbor/core/mem.c), and [dobject](https://github.com/lexborisov/lexbor/blob/master/source/lexbor/core/dobject.c).

4. And whether it is necessary? At the moment, I'm completely satisfied with the standard `malloc`.
