### ISSUE TITLE
tagged template literal is not parsed correctly

### ISSUE THREAD

**Issue by Dan-Do** [lexbor/lexbor#101]
```html
<div>${ () => console.log('foo') }</div>
```
the lib auto encode the html entities, in this case the arrow function `=>` becomes `=&gt;` which is wrong.

**Comment by lexborisov** [comment]
@Dan-Do 

It is correct behavior.
[Serializing HTML](https://html.spec.whatwg.org/multipage/parsing.html#serialising-html-fragments) by specification. Take a look `If current node is a Text node` section.

For JS code use `<script>` tag. In this tag, the date is not converted.

**Comment by Dan-Do** [comment]
In my opinion, the text inside ${ ... } is actually a script tag. Or may be it belongs to ES6 javascript scope but not HTML scope.

**Comment by lexborisov** [comment]
@Dan-Do 

`HTML` is not `JavaScript`, all yours JS must be included in to `<script>` tag.

**Comment by Dan-Do** [comment]
Okay, thank you for the answer.
