### ISSUE TITLE
lxb_dom_element_first_attribute_noi return not null element, on LXB_TAG__TEXT node

### ISSUE THREAD

**Issue by kostya** [lexbor/lexbor#102]
on such html i get segfault: https://github.com/kostya/lexbor/issues/5#issuecomment-735407307, it is because lxb_dom_element_first_attribute_noi return not null pointer, on LXB_TAG__TEXT node. Is it expected behaviour? In myhtml all is ok in this case. And should i check node tag before requiring lxb_dom_element_first_attribute_noi ? (lexbor at commit 3cf192ff8106a78a942bc0ad8b4d5e9e30a4c0b3)

**Comment by lexborisov** [comment]
Hi @kostya

Most likely you are trying to use text nodes as an HTML element, which is wrong.
Take a look list of [DOM interfaces](https://dom.spec.whatwg.org/#node-trees) and [Text interface](https://dom.spec.whatwg.org/#text).

In lexbor, please use `lxb_dom_text_t *`:
```C
lexbor_str_t *str;
lxb_dom_text_t *text;

text = lxb_dom_interface_text(text_node);
str = &text->char_data.data;

printf("%.*s", (int) str->length, str->data);
```

**Comment by kostya** [comment]
ok, if its not bug closing it, i will try this. question what lxb_dom_interface_text return for not text nodes?

**Comment by lexborisov** [comment]
@kostya 

> what lxb_dom_interface_text return for not text nodes?

Garbage.

**Comment by kostya** [comment]
request lxb_dom_element_first_attribute_noi for doctype node also produce segfault. is there list of node tags where i shouldn't call this?
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
```

**Comment by lexborisov** [comment]
@kostya 

[DOM Document type](https://dom.spec.whatwg.org/#interface-documenttype) has its own interface, please take a look [doctype interface](https://github.com/lexbor/lexbor/blob/master/source/lexbor/dom/interfaces/document_type.h).

Use:
```C
lxb_dom_document_type_t *doctype;

doctype = lxb_dom_interface_document_type(node);
```

And [look all interfaces](https://github.com/lexbor/lexbor/tree/master/source/lexbor/dom/interfaces) for nodes in lexbor.
