### ISSUE TITLE
vector graphic resources

### ISSUE THREAD

**Issue by vtorri** [lexbor/lexbor#103]
edge flag algorithm by Kallio : 

http://mlab.uiah.fi/~kkallio/antialiasing/EdgeFlagAA.pdf
web site : http://mlab.uiah.fi/~kkallio/antialiasing/

lib that is using it :  enesim : https://github.com/turran/enesim

other links : 
https://lists.cairographics.org/archives/cairo/2007-August/011136.html
https://lists.cairographics.org/archives/cairo/2007-August/thread.html#11137   <--- search for "Survey of polygon rasterization techniques"

**Comment by lexborisov** [comment]
@vtorri 

Thank you, I have studied the material you cited. I'll keep it in mind.
