### ISSUE TITLE
Function for decode html entities

### ISSUE THREAD

**Issue by kostya** [lexbor/lexbor#104]
Hi, 2 questions:

1) Before update of 1.0, i using `lxb_html_parser_char_ref_data`, but now there is no such function. Is there any alternative?
 
2) When using tokenizer, if i store tokens, and later try to get tag text by `text_start`, `text_end` (from `lxb_html_token_t`), it returns bad strings, so it relevant only when parsing, is it right? (So for such use case i should use `begin` and `end` variables and some custom decode html entites function).

**Comment by lexborisov** [comment]
Hi @kostya 

1. No, it is not needed, everything that this function was doing now happens during tokenization.
2. If token is one of  String/CDATA/Text then `text_start`, `text_end` have a start and end position form internal buffer, not incoming. That is, this is already processed data. We only have one token, we don't create many of them. Therefore, if you want to save some processed data from the token, you need to copy it. This approach accelerated the processing and construction of the tree, and also helped to significantly simplify the code.

**Comment by kostya** [comment]
Ok, i see, but i think still need this method for custom decode entities, because imagine usecase: I store some of tokens, and process them later, and later i need Text data from some of them (little amount), but if i would copy every Text data, it would be big overhead.

**Comment by lexborisov** [comment]
@kostya 

I can back all handlers for processing data, but without chunks support.

**Comment by kostya** [comment]
Is it possible also add option for tokenizer to not process data? just to skip all this overhead, when you not need it.

**Comment by lexborisov** [comment]
@kostya 

> Is it possible also add option for tokenizer to not process data? just to skip all this overhead, when you not need it, and going to process it manually.

This will greatly complicate the code. 
The gain is minimal, but the implementation and support costs are huge.
