### ISSUE TITLE
The project is still developing?

### ISSUE THREAD

**Issue by Friedrich777** [lexbor/lexbor#106]
The project is still developing?

**Comment by lexborisov** [comment]
@Friedrich777 

Hi!

Of course, the project is not abandoned. I develop this project in my free time of the main work.

Soon the load on the main work will decrease and I will start the modified CSS parser and selectors. They are ready but require testing.

**Comment by Friedrich777** [comment]
how can I contact you about cooperation. I speak Russian?

**Comment by vtorri** [comment]
you can still open issues for technical discussions. I'm also interested in this project.

One of the modification is for example another build system (instead of cmake), based on configure scripts, inspired by 

https://github.com/nginx/njs

Vincent

**Comment by lexborisov** [comment]
> @lexborisov
> how can I contact you about cooperation? I speak Russian

@Friedrich777 

`lex.borisov@gmail.com` or telegram `lexborisov`.
