### ISSUE TITLE
Lexbor is now available in MacPorts

### ISSUE THREAD

**Issue by ryandesign** [lexbor/lexbor#107]
Hi, I just wanted to let you know I added lexbor to MacPorts. MacPorts users on macOS can now install lexbor simply by running:
```
sudo port install lexbor
```
We currently produce binaries for every macOS version from 10.6.x to 11.x inclusive.

You are welcome to mention this installation method on your web site if you would like. If you would like a URL that you can mention along with it, a good URL to use is https://ports.macports.org/port/lexbor.

**Comment by lexborisov** [comment]
@ryandesign 

This is awesome!
I will post this link in the project (README and site).

Thank you!
