### ISSUE TITLE
Html parsing mistakenly nests divs

### ISSUE THREAD

**Issue by foobar27** [lexbor/lexbor#108]
Hi,

I think I found a bug in the parsing for broken html documents, for example for the following page (unfortunately the original page is not accessible anymore, so I had to upload it here):  [input.html.gz](https://github.com/lexbor/lexbor/files/6489131/input.html.gz).

I am not sure if it is related, but it is remarkable that this file contains two `<div id="edit2228954">` (one is a descendant of the other). The same applies for `<div id="edit2228952">`.

The latest version of lexbor makes e.g. the first occurrence of `<div id="edit2228954">` a descendant of the first occurrence of `<div id="edit2228952">`.  In chrome and firefox, these divs are at the same level, they are not descendants. In myhtml (not lexbor) with SHA1 58dfb5e916119aa7f4386dd688907d096c1fa3d1 it is also correct.

I basically decompress the input file, and use an adapted version of the `html2sexpr` program to print the html tree (instead of just the first child):
```
-    status = tree_walker(lxb_dom_interface_node(document)->first_child,
-                         serialize_cb, NULL);
+    serialize(lxb_dom_interface_node(document));
```

Could you have a look please?

Thanks for your help!

Sébastien

**Comment by lexborisov** [comment]
@foobar27 

Sébastien, thanks for the report!

Fixed.
