### ISSUE TITLE
Lexbor is now available in Homebrew

### ISSUE THREAD

**Issue by Puasonych** [lexbor/lexbor#111]
I'm writing to let you know that Lexbor was successfully added to Homebrew. 

```
brew install lexbor
```

[The current brew formula.](https://github.com/Homebrew/homebrew-core/blob/master/Formula/lexbor.rb) 🚀

**Comment by lexborisov** [comment]
@Puasonych 

Awesome!

I updated the `README.md` and the site.

Thanks Erik.
