### ISSUE TITLE
question: parse HTML fragments

### ISSUE THREAD

**Issue by kevinsjoberg** [lexbor/lexbor#112]
I'm trying to use lexbor to parse HTML provided by the user and then translate whatever they provided into my DSL. The input can be a complete HTML document or HTML fragments.

Some examples of translations I'm trying to achieve:

```html
<h1>Hello</h1>
```

```crystal
h1 "Hello"
```
---

```html
<template>
  <h1>Hello</h1>
</template>
```

```crystal
template do
  h1 "Hello"
end
```

---- 

```html
<html>
<head>
  <meta charset="utf-8">
  <title>My Title</title>
</head>
<body>
  <h1>Hello</h1>
</body>
</html>
```

```crystal
head do
  meta charset: "utf-8"
  title "My Title"
end

body do
  h1 "Hello"
end
```

What I'm struggling with, is finding a way to get the expected nodes for the above three examples without having to rely on "hacks". Any guidance would be much appreciated.

**Comment by lexborisov** [comment]
Hi @kevinsjoberg 

Have you seen an [example](https://github.com/lexbor/lexbor/blob/master/examples/lexbor/html/elements_by_tag_name.c)?

**Comment by kevinsjoberg** [comment]
Thanks for reaching out, @lexborisov. 🙂 I've seen the example, but look at what's being parsed for each example.

```html
<h1>Hello</h1>
```

```html
<html>
  <head>
  </head>
  <body>
    <h1>
      "Hello"
    </h1>
  </body>
</html>
```
---

```html
<template>
  <h1>Hello</h1>
</template>
```

```html
<html>
  <head>
    <template>
      #document-fragment
        <h1>
          "Hello"
        </h1>
    </template>
  </head>
  <body>
  </body>
</html>
```

---- 

```html
<html>
<head>
  <meta charset="utf-8">
  <title>My Title</title>
</head>
<body>
  <h1>Hello</h1>
</body>
</html>
```

```html
<html>
  <head>
    <meta charset="utf-8">
    <title>
      "My Title"
    </title>
  </head>
  <body>
    <h1>
      "Hello"
    </h1>
  </body>
</html>
```

Given what I want to achieve, it's hard to find all nodes provided by the user. The `template` ends  up in the `head` for example while the first example end up in the `body`. It's also impossible from this, to see if the user provided a fragment or a full document (as seen in the last example) since the output is the same.

**Comment by kostya** [comment]
I think there is no way in current parser, you should know what you parse html or fragment

**Comment by kevinsjoberg** [comment]
@kostya given it's user provided input, it's impossible for me to know without falling back to guessing using a regex or similar methods.

**Comment by kevinsjoberg** [comment]
@lexborisov do you think its possible? I guess the alternative would be to write my own parser that doesn't care about the semantics, just proper translation.

**Comment by lexborisov** [comment]
@kevinsjoberg 

I don't fully understand the problem. After parsing, you don't need the elements: `<html>`, `<head>` and so on?
Try [parsing HTML fragment](https://github.com/lexbor/lexbor/blob/master/source/lexbor/html/parser.h#L70).

```C
    lxb_html_element_t *root;
    lxb_dom_node_t *html_node;
    lxb_html_document_t *document;

    static const lxb_char_t name[] = "div";

    static const lxb_char_t html[] = "<h1>Hello</h1>";
    size_t html_len = sizeof(html) - 1;

    document = lxb_html_document_create();
    if (document == NULL) {
        FAILED("Failed to create HTML Document");
    }

    root = lxb_html_document_create_element(document, name, sizeof(name) - 1, NULL);
    if (root == NULL) {
        return EXIT_FAILURE;
    }

    html_node = lxb_html_document_parse_fragment(document, &root->element, html, html_len);
    if (html_node == NULL) {
        return EXIT_FAILURE;
    }
```

For:
```HTML
<h1>Hello</h1>
```
Result:
```HTML
<html>
  <h1>
    "Hello"
  </h1>
</html>
```

For
```HTML
<template>
  <h1>Hello</h1>
</template>
```

```HTML
<html>
  <template>
    #document-fragment
      <h1>
        "Hello"
      </h1>
  </template>
</html>
```

**Comment by kevinsjoberg** [comment]
@lexboriso

Let me try to explain. We provide https://luckyframework.org/html, allowing users to put in arbitrary HTML that we translate into our own framework specific DSL. The user may submit a fragment, or a whole document. I want to ensure I only translate exactly what they provided.

In your example, a full document would fail. Since

```html
<html>
<head>
  <meta charset="utf-8">
  <title>My Title</title>
</head>
<body>
  <h1>Hello</h1>
</body>
</html>
```

result in 

```html
<html>
  <meta charset="utf-8">
  <title>
    "My Title"
  </title>
  <h1>
    "Hello"
  </h1>
</html>
```

Perhaps, I need to "guess" if the user provided a full document or not, and then conditionally call the proper thing in Lexbor?

**Comment by lexborisov** [comment]
@kevinsjoberg 

Then @kostya was right, you really need to know what exactly the user is sending you: full HTML document or HTML fragment.
Perhaps you need to give the user a choice. Some kind of checkbox.
If you want to provide the user with full HTML parsing, this is the only way.

**Comment by kevinsjoberg** [comment]
Thanks! Makes sense. 🙂
