### ISSUE TITLE
Difference in css selectors with modest

### ISSUE THREAD

**Issue by kostya** [lexbor/lexbor#114]
I made some tests on css selectors, and most cases works ok, but this cases failed:

```html
      <div>
        <p id=p1>
        <p id=p2 class=jo>
        <p id=p3>
          <a href="some.html" id=a1>link1</a>
          <a href="some.png" id=a2>link2</a>
        <div id=bla>
          <p id=p4 class=jo>
          <p id=p5 class=bu>
          <p id=p6 class=jo>
        </div>
      </div>
```

1. `div > :nth-child(2n+1):not(:has(a))`
Modest: ["p1", "p4", "p6"]
Lexbor: ["a1", "a2"]

2) `p[id=p3] > a:matches([href *= "html"], [href $= ".png"])`
Modest: ["a1", "a2"]
Lexbor: []

**Comment by lexborisov** [comment]
@kostya 

1. Yeah, my mistake. Fixed.
2. In Selectors Version 4 `:matches()` [renamed](https://drafts.csswg.org/selectors-4/#changes-2018-02) to `:is()`. Check the [status and log](https://github.com/lexbor/lexbor/blob/master/examples/lexbor/css/selectors/list_easy_way.c#L54) after parsing.

I can add `:matches` as an alias for `:is`.
