### ISSUE TITLE
lxb_dom_node_text_content and document element

### ISSUE THREAD

**Issue by rushter** [lexbor/lexbor#116]
I think it makes sense to add support for document (root) element to the `lxb_dom_node_text_content` function.
When extracting the whole text, people often want to include the title as well.

Currently, this code won't work:
```
lxb_html_document_t *document;
lxb_dom_node_text_content((lxb_dom_node_t *) document, &len);
```

Another reason to add this is universality, so the user of the library does not need to check the node type before passing it to the function. My test failed because I was testing the same function on the `document` and `body` nodes.  From my perspective (as a user of a library), such nodes should behave the same.

**Comment by lexborisov** [comment]
@rushter 

This behavior [by DOM specification](https://dom.spec.whatwg.org/#dom-node-textcontent). Try to execute in the browser:
```HTML
<script>
    console.log(document.textContent);
</script>
```

Result: `null`

I can only add some kind of function that will work with a document.

**Comment by lexborisov** [comment]
@rushter 

It turns out everything is already there!

```C
    size_t len;
    lxb_dom_node_t *root = (lxb_dom_node_t *) lxb_dom_document_root(&document->dom_document);

    lxb_char_t *text = lxb_dom_node_text_content(root, &len);

    printf("%s\n\n", (char *) text);

    lxb_dom_document_destroy_text(&document->dom_document, text);
```

**Comment by rushter** [comment]
Thanks!
