### ISSUE TITLE
Code duplication when parsing malformed HTML

### ISSUE THREAD

**Issue by rushter** [lexbor/lexbor#117]
Not sure if there is a way to ignore this instead of duplicating the code. Using nested `a` tags is against standards, but there are plenty of such websites.

Simple example:
```
<a href="https://lexbor.com">
  <noscript>
   <a href="/test">
   </a>
  </noscript>
</a>
```

Will be transformed to (Lexbor/Modest):

```
<html><head></head><body><a href="https://lexbor.com">
  </a><noscript><a href="https://lexbor.com">
   </a><a href="/test">
   </a>
  </noscript>
</body></html>
```

Chrome:

```
<html><head></head><body><a href="https://lexbor.com">
  <noscript>
   <a href="/test">
   </a>
  </noscript>
</a></body></html>
```

Another example:

```
<a href="/lexbor">Sad
    <div>Bug
      <a href="/members/">Href</a>
    </div>
</a>
```

Lexbor/Modest:

```
<html><head></head><body><a href="/lexbor">Sad
    </a><div><a href="/lexbor">Bug
      </a><a href="/members/">Href</a>
    </div>
</body></html>

```
Chrome and Firefox fail on the second example as well:

```
<html><head></head><body><a href="/lexbor">Sad
  </a><div><a href="/lexbor">Bug
    </a><a href="/members/">Href</a>
  </div>

</body></html>
```

**Comment by lexborisov** [comment]
@rushter 

This is the correct behavior in the absence or switched off `JS`.
[Disable JS in `chrome`](https://stackoverflow.com/questions/13405383/how-to-disable-javascript-in-chrome-developer-tools/13405409) and you will have the same result.

In the Document we have a switcher `document->dom_document.scripting` it changes the parsing behavior.
We can enabled it before parsing. Need to think.

**Comment by lexborisov** [comment]
@rushter 

Now you can change the behavior of HTML parsing (for `<noscript>` tag).
As if there is script support or not (default).

For Document:
```C
    lxb_html_document_t* document = lxb_html_document_create();
    
    lxb_dom_document_scripting_set(&document->dom_document, true);
```

For Parser:
```C
    lxb_html_parser_t *parser = lxb_html_parser_create();
    lxb_status_t status = lxb_html_parser_init(parser);
    if (status != LXB_STATUS_OK) {
        lxb_html_parser_destroy(parser);
        return EXIT_FAILURE;
    }

    lxb_html_parser_scripting_set(parser, true);
```

About your example: example:
```HTML
<a href="/lexbor">Sad
    <div>Bug
      <a href="/members/">Href</a>
    </div>
</a>
```
The result is correct:
```HTML
<html><head></head><body><a href="/lexbor">Sad
    </a><div><a href="/lexbor">Bug
      </a><a href="/members/">Href</a>
    </div>
</body></html>
```

Another link will be added to the `div`, as the algorithm for restoring the broken html will work.
[Specification](https://html.spec.whatwg.org/multipage/parsing.html#unclosed-formatting-elements)

**Comment by rushter** [comment]
@lexborisov Thanks!

BTW, is there a way to fix similar problems without patching the code? https://github.com/lexborisov/Modest/issues/86

I've fixed this by changing the parsing behavior of the iframe tag to div in the code.
Can I somehow modify the handling of the iframe in runtime, i.e. by changing the value in a struct that stores meta data about the iframe tag?

Such problems are not related to your engine, but it would be cool to have a way to alter parsing behavior.

**Comment by lexborisov** [comment]
@rushter 

Unfortunately, there is no easy way. Only adding callbacks.
