### ISSUE TITLE
Setting existing attributes leads to segfault

### ISSUE THREAD

**Issue by rushter** [lexbor/lexbor#120]
Example: https://github.com/lexbor/lexbor/blob/58fc5f4834fd5562cf5e228294e391694a66599d/examples/lexbor/html/element_attributes.c#L27

Please change  `my-name` to `id` to get a segfault.

```
./lexbor/html/element_attributes
HTML:
<div id=my-best-id></div>

Tree after parse:
<html>
  <head>
  </head>
  <body>
    <div id="my-best-id">
    </div>
  </body>
</html>
[1]    31283 segmentation fault  ./lexbor/html/element_attributes
```

**Comment by lexborisov** [comment]
@rushter 

Fixed.
Thanks for the report!
