### ISSUE TITLE
Raw value support

### ISSUE THREAD

**Issue by rushter** [lexbor/lexbor#121]
In Modest, it's possible to retrieve the raw value (undecoded text) of a node using `myhtml_tree_node_t.token.element_begin` and `myhtml_tree_node_t.token.element_length`.

Is it possible in lexbor? I see `lxb_html_token_t.text_start` but it looks like such data is not available after the parsing.

**Comment by lexborisov** [comment]
@rushter 

Practice has shown that no one uses this.

> Is it possible in lexbor? I see lxb_html_token_t.text_start but it looks like such data is not available after the parsing.

You are right, the token contains the information you need, but after building the tree, you do not have access to the token, it is destroyed (and generally one token using for all parsing).

Positions from the token can be saved to the DOM Node, but it seems this is meaningless information that will only take up memory.
It may be possible to add a certain `debug` field to the DOM Node in which to save such information if an additional flag is specified before parsing HTML?

I don't know how to do it "beautifully" yet.

**Comment by rushter** [comment]
Thanks. That's not a big deal.
