### ISSUE TITLE
Parsing ASCII-incompatible HTML documents

### ISSUE THREAD

**Issue by phoerious** [lexbor/lexbor#127]
Perhaps this just isn't documented, but it looks like you cannot use Lexbor for parsing ASCII-incompatible HTML documents.
Parsing documents that are encoded with some western encoding or UTF-8 seems to work (you simply get the raw bytes of text nodes), but parsing something like a UTF-16-encoded document isn't possible without decoding it first and then re-encoding it as UTF-8.

Is this by design? Am I supposed to re-encode ASCII-incompatible documents or is there a way to make the parser encoding-aware?

**Comment by lexborisov** [comment]
@phoerious 

You can get encoding from the HTTP header: `Content-Type`.
Example: `Content-Type: text/html; charset=windows-1251`.

If HTTP headers are not available, then you can find the encoding in the HTML document by tag `meta`.
For example:
1. `<meta charset='windows-1251'>`
2. `<meta http-equiv="content-type" content="text/html; charset=windows-1251">`

Take a look:
1. Encoding name [from HTTP `Content-Type` value](https://github.com/lexbor/lexbor/blob/master/source/lexbor/html/encoding.h#L44).
2. [Encoding name from HTML](https://github.com/lexbor/lexbor/blob/master/examples/lexbor/html/encoding.c) before parsing.
3. Handlers (encode/decode) by [encoding name](https://github.com/lexbor/lexbor/blob/master/source/lexbor/encoding/encoding.h#L28).
4. Handlers [by name](https://github.com/lexbor/lexbor/blob/master/examples/lexbor/encoding/data_by_name.c).
5. Encode/Decode [examples](https://github.com/lexbor/lexbor/tree/master/examples/lexbor/encoding).

P.S.: It may be necessary to add a simplified API Encoding/Decoding.

**Comment by phoerious** [comment]
I am not talking about detecting the encoding. I am talking about parsing UTF-16 (or 32) encoded HTML, which doesn't seem possible at the moment without re-encoding it as UTF-8 beforehand.

**Comment by lexborisov** [comment]
@phoerious 

How do you imagine a parser that will parse UTF-16 without re-encoding? Write two/three parsers?
The parser works with UTF-8. Convert your data to this format.
Any parser that supports different encodings as input will re-encoding data inside.

**Comment by phoerious** [comment]
I was thinking more about lazy decoding where the parser is aware of the input encoding in order to be able to read the tags, but doesn't do anything with text nodes, which is pretty much how it works at the moment, but only as long as the input is ASCII-compatible in the lower 7 bits. That is, I can parse any CP1252-encoded text without re-encoding it, even if it's not valid UTF-8, and when I read the contents of a text node, I get back the verbatim byte sequence. Unfortunately, this breaks down as soon as HTML tags are not ASCII-compatible anymore.

Background: I'm working on integrating Lexbor with our Cython web archive parsing library Resiliparse (https://resiliparse.chatnoir.eu/en/latest/man/parse.html) for faster HTML processing and I would like to avoid decoding the byte string unless absolutely necessary. The main reason for this is that in the end, I will have to decode the byte string into a Python Unicode string anyway, no matter its previous encoding. So when I read the raw byte stream from, say, a WARC file, I would have to decode it first and then encode it again for Lexbor and then do the same thing a second time for Python.

**Comment by lexborisov** [comment]
@phoerious 

You are right, conversions cannot be avoided:
`stream -> code points -> utf-8 -> parser -> Python`

Converting encodings is part of HTML parsing.
Encoding and HTML parser supports chunks. It is not necessary to accumulate a full buffer.
I do not see something terrible here. In any other case, it will be difficult to develop and maintain HTML parsing.

**Comment by phoerious** [comment]
I'm not worried about the memory cost. The processing time is what I want to keep down. Thing is, were working with tera and petabytes of web data, so our algorithms better be fast. Any additional conversion costs a lot of time at that scale.
I can see that lazy decoding may be too complicated to implement, but it could avoid a lot of redundant extra work. We also have a lot of additional logic for dealing with incorrect or broken encodings, but at that point we're already in Python land, so that's too late and Lexbor doesn't provide the needed primitives for that out of the box.

**Comment by lexborisov** [comment]
@phoerious 

> I can see that lazy decoding may be too complicated to implement, but it could avoid a lot of redundant extra work.

I'm sure the benefits won't matter as much as the difficulty of maintaining all of this. It is faster to convert a block of memory, what to do lazy conversions with checks and function calls for each character. But this is all theory.

I hope you find what you are looking for.

**Comment by phoerious** [comment]
I guess I have to re-encode the text then in order to normalize it before I can parse it. Doing it with Python right now, will see if that's fast enough or if I have to use Lexbor's low-level primitives for that.

**Comment by lexborisov** [comment]
@phoerious 

[Take a look Selectolax](https://github.com/rushter/selectolax#available-backends).

**Comment by phoerious** [comment]
I know Selectolax. I fixed some encoding issues with the MyHTML backend in the past there. The experimental Lexbor backend doesn't seem to care much about ensuring that the input is properly encoded.

**Comment by lexborisov** [comment]
@phoerious 

I'm sure you can ask the author to add encodings support for lexbor backend. It doesn't look very complicated.

**Comment by phoerious** [comment]
I'm writing my own Lexbor wrapper. Selectolax is a great standalone HTML library, but it is is very hard to integrate it properly into our pipeline as a dependency.
