### ISSUE TITLE
Windows 64 bits: huge number of warnings in tests

### ISSUE THREAD

**Issue by vtorri** [lexbor/lexbor#128]
Exemple:

```
E:/Documents/programmes_x64/msys2/home/vtorri/gitroot_64/lexbor/test/lexbor/html/tree/open_elements.c:82:5: note: in expansion of macro 'test_eq_size'
   82 |     test_eq_size(lexbor_array_length(tree->open_elements), 3UL);
```

warning:

```
E:/Documents/programmes_x64/msys2/home/vtorri/gitroot_64/lexbor/test/unit/test.h:216:29: warning: format '%Iu' expects argument of type 'size_t', but argument 4 has type 'long unsigned int' [-Wformat=]
```

The reason: contrary to most UNIX, 3UL is an unsigned long and on Windows 64 bits, it's a 32 bits type. See [64 bits data models](https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models)

A solution would be to cast to `size_t` the value in test_eq_size() macro

**Comment by vtorri** [comment]
and in test_ne_size macro

**Comment by lexborisov** [comment]
@vtorri 

Thanks for the report! 
Fixed.
