### ISSUE TITLE
huge number of warnings with -Wextra

### ISSUE THREAD

**Issue by vtorri** [lexbor/lexbor#129]
mainly, 2 kinds of warnings:

```
warning: unused parameter
warning: comparison of integers of different signs
```

@lexborisov is it worth fixing them ?

**Comment by lexborisov** [comment]
@vtorri 

Where does this happen?

**Comment by vtorri** [comment]
output: 
[lexbor_warnings.txt](https://github.com/lexbor/lexbor/files/7099259/lexbor_warnings.txt)

**Comment by lexborisov** [comment]
@vtorri 

All warnings have been [fixed](https://github.com/lexbor/lexbor/commit/4c17bea6b9114e37c3f92dc0e896b9e5089eea9f).
Build for Windows works well. Now you can run tests under Windows too.

1. `cmake . -DLEXBOR_BUILD_TESTS=ON -DLEXBOR_BUILD_EXAMPLES=ON` or use CMake CLI.
2. Open lexbor.sln and build it.
3. Run `ctest`.

Thanks for the initial patch.
