### ISSUE TITLE
force c99 compilation

### ISSUE THREAD

**Issue by vtorri** [lexbor/lexbor#130]
afaik, lexbor is a project that is c99 compliant. Why not force compilation with `-std-c99 -Wpedantic` on non MSVC environment ?

**Comment by lexborisov** [comment]
@vtorri 

I'll try to test with these flags.

**Comment by vtorri** [comment]
any news on this ?

**Comment by vtorri** [comment]
if I'm not mistaken, -pedantic -std=c99 is passed to the compiler in config.make in port/

feel free to close this issue
