### ISSUE TITLE
Windows: useless code in port/windows_nt/config.cmake

### ISSUE THREAD

**Issue by vtorri** [lexbor/lexbor#131]
https://github.com/lexbor/lexbor/blob/master/source/lexbor/ports/windows_nt/config.cmake#L1

lines 1 to 7 are useless : all the Windows compilers define `_WIN32` and `_WIN64` like that : 

 * they all define `_WIN32`, for both 32 and 64 bits compilers
 * `_WIN64` is defined only for 64 bits compilers

**Comment by lexborisov** [comment]
@vtorri 

I bought a PС, installed Visual Studio 2019 and am ready to start supporting for Windows. Could you write an instruction on what to install: gnu tools? I know Windows very badly.

**Comment by vtorri** [comment]
If you have visual studio installed, then you can use cmake to create a Visual Studio solution, just call cmake as usual except with `cmake -G "Visual Studio 16 2019" -A x64`

Add the cmake options you want. Normally, it creates a file : lexbor.sln and open this file with Visual Studio

to compile, in Visual Studio, just hit : Ctrl-Shift-b

**Comment by vtorri** [comment]
fixed in git, close

@lexborisov  if you have questions about Windows, you can send me mails

**Comment by lexborisov** [comment]
@vtorri 

Thanks!
