### ISSUE TITLE
SVG title crashes lxb_html_document_title() if HTML document has no title of its own

### ISSUE THREAD

**Issue by phoerious** [lexbor/lexbor#134]
`lxb_html_document_title()` crashes when the document does not have a `<title>` element of its own, but contains an SVG with a `<title>` element somewhere in the body.

Minimal HTML document to crash `lxb_html_document_title()`:

```html
<!doctype html>
<svg xmlns="http://www.w3.org/2000/svg"><title>Foo</title></svg>
```
Inserting a `<title>` element before that prevents the crash:

```html
<!doctype html>
<title></title>
<svg xmlns="http://www.w3.org/2000/svg"><title>Foo</title></svg>
```

**Comment by lexborisov** [comment]
@phoerious 

Retrieving the title (HTMLTitleElement) is only available in the HTML namespace.

Title element in the SVG namespace:
```HTML
<!doctype html>
<svg xmlns="http://www.w3.org/2000/svg"><title>Foo</title></svg>
```

Title element in the HTML namespace:
```HTML
<!doctype html>
<title></title>
<svg xmlns="http://www.w3.org/2000/svg"><title>Foo</title></svg>
```

Thanks for the report!
Fixed.

**Comment by phoerious** [comment]
Yeah, I expected something like that. There are probably more bugs like that going to appear once we're starting to crunch through more web archive data.

BTW would it be possible to provide a similar function for retrieving the first element that matches a certain ID (i.e., an implementation of getElementById())? Since you can stop traversing the tree after the first match, that would be way more efficient than scanning the whole DOM for ID attribute matches only to discard everything but the first match. I could implement my own DOM walker that does that, but that's kind of inconvenient. Unless of course, Lexbor already supports that and I just didn't find it.

**Comment by lexborisov** [comment]
@phoerious 

> matches a certain ID (i.e., an implementation of getElementById())

You can use [lxb_dom_elements_by_attr()](https://github.com/lexbor/lexbor/blob/master/source/lexbor/dom/interfaces/element.h#L145). [Example](https://github.com/lexbor/lexbor/blob/master/examples/lexbor/html/elements_by_attr.c). But it will search for all nodes.

You can use [simple_walk](https://github.com/lexbor/lexbor/blob/master/source/lexbor/dom/interfaces/node.h#L108) to create your own node search.

Or you can use CSS Selector. Take a look [example](https://github.com/lexbor/lexbor/tree/master/examples/lexbor/selectors). You can create a selector (selectors) and use it many times for different documents.

**Comment by phoerious** [comment]
Yeah, no. I need the walker solution, but as I said, that's pretty inconvenient. Since getElementById() is a standard DOM function, I think Lexbor should have a convenience implementation for it.

**Comment by lexborisov** [comment]
@phoerious 

>  Since getElementById() is a standard DOM function, I think Lexbor should have a convenience implementation for it.

You can create issue for this :)
