### ISSUE TITLE
Is it possible to provide a simple data extraction example?

### ISSUE THREAD

**Issue by diracsbracket** [lexbor/lexbor#138]
Hello,
I have been looking throughout the examples in order to try and learn how to use this library, but I must admit to my great shame that I am still at a loss...

I was hoping to use the Lexbor library to extract text data from webpages by
1. first locating the data via element ID or via a CSS selector
2.  obtaining the text data (inner HTML ?) from that element.

Would it be possible for anyone to provide a short example on how to do this, both with
HTML functions (elements by ID) and with CSS selector?

Many embarrassed thanks...

**Comment by rushter** [comment]
There are examples in C https://github.com/lexbor/lexbor/blob/master/examples/lexbor/selectors/

**Comment by diracsbracket** [comment]
@rushter
Yes, tried those examples, but it is not clear how to get the text/inner html then from the nodes that are found.

**Comment by lexborisov** [comment]
@diracsbracket 

1. Use [lxb_dom_node_text_content()](https://github.com/lexbor/lexbor/blob/0c4010b10a922a45513d67beec0ddd29c2951f85/source/lexbor/dom/interfaces/node.h#L116), but it allocate memory.
2. Or use navigate `node->first_child`, `node->next` and so on to find text does.
3. Or use tree walker to find text nodes:
```C
lxb_dom_node_simple_walk(node, text, NULL);

static lexbor_action_t
text(lxb_dom_node_t *node, void *ctx)
{
    if (node->type != LXB_DOM_NODE_TYPE_TEXT) {
        return LEXBOR_ACTION_OK;
    }

    lxb_dom_character_data_t *ch_data = &lxb_dom_interface_text(node)->char_data;

    printf("%.*s", (int) ch_data->data.length, (const char *) ch_data->data.data);

    return LEXBOR_ACTION_OK;
}
```

**Comment by patrick-luck** [comment]
If it wouldn't be too much trouble, would it be possible to see the above code in a compilable example please?

I have tried to incorporate ` lxb_dom_node_text_content()` into an existing example (text.c) without success.

Like OP, I am looking to extract the inner data from between two tags after finding the data by its header (e.g. seen below as "choose-this-header") and to then print the value `0.7`:

`<td headers="choose-this-header">0.7</td>`

Thank you

**Comment by lexborisov** [comment]
And [take a look](https://stackoverflow.com/questions/69827153/lexbor-webscraping-an-html-table-in-c).
