### ISSUE TITLE
Regression: head and body selection broken on Git master

### ISSUE THREAD

**Issue by phoerious** [lexbor/lexbor#140]
Head and body selection is broken on Git, but works in 2.1.0. This is a regression introduced in 0c4010b10a922a45513d67beec0ddd29c2951f85.

Reproduction example:
```c
#include <lexbor/html/html.h>

void serialize(lxb_dom_element_t* node, lxb_dom_document_t* document) {
    if (!node) {
        printf("NULL\n");
        return;
    }

    lexbor_str_t* html_str = lexbor_str_create();
    lxb_html_serialize_tree_str(lxb_dom_interface_node(node), html_str);
    printf("%s\n", html_str->data);
    lexbor_str_destroy(html_str, document->text, true);
}

int main(void) {
    static const lxb_char_t html[] = "<!doctype html><html><head></head><body></body></html>";
    lxb_html_document_t* html_document = lxb_html_document_create();
    lxb_html_document_parse(html_document, html, sizeof(html) - 1);
    lxb_dom_document_t* document = &html_document->dom_document;

    printf("HEAD:\n");
    lxb_dom_element_t* head = lxb_dom_interface_element(lxb_html_document_head_element(html_document));
    serialize(head, document);

    printf("\nBODY:\n");
    lxb_dom_element_t* body = lxb_dom_interface_element(lxb_html_document_body_element(html_document));
    serialize(body, document);

    return 0;
}
```

Expected result:
```
HEAD:
<head></head>

BODY:
<body></body>
```

Result after 0c4010b10a922a45513d67beec0ddd29c2951f85:
```
HEAD:
NULL

BODY:
<head></head>
```

`head` is `NULL` and `body` contains the head element instead of the body.

**Comment by lexborisov** [comment]
@phoerious 

Something I am doing wrong:
```HTML
HEAD:
<head></head>

BODY:
<body></body>
```
Current GitHub code.

**Comment by phoerious** [comment]
Make sure you are using the correct version of the library also at runtime. When I set `LIBRARY_PATH` and `LD_LIBRARY_PATH` path to the CMake build dir, I can reproduce the bug. As soon as I unset `LD_LIBRARY_PATH`, the bug is gone, because the 2.1.0 release installed via apt ist used.

**Comment by phoerious** [comment]
I figured out what's going on here: Turns out, this happens if you have the old headers in your `CPATH` during compilation, but are linking against the new version. Are there some ABI incompatibilities between the versions?

**Comment by vtorri** [comment]
Normally, this library has been released with a major version too early. The conventional naming scheme is : 

 * first release : 0.0.0 (in the form major_version.minor_version.micro_version)
 * before a release : 
   - if only fixed bugs : micro_version++
   - if API is added : minor_version++ and micro_version set to 0
   - if API or API are broken : major_version++ and  micro_version and minor_version set to 0

Note that setting a major version is an important step. It means that the API must be stable during the development. Imho, the current lexbor version should have been something like 0.*.*, like 0.2.4

I don't know if it is possible to restart from the beginning the versionning, but i think it is too late.

**Comment by phoerious** [comment]
Sorry to nag, but would it be possible to make a new release soon? The develop branch has various fixes for issues with the current stable release for which no workaround exist as well as some issues for which workarounds exist that I would like to get rid of.

**Comment by lexborisov** [comment]
@phoerious 

If within a week I do not publish the parser of the CSS properties, then there will be a release.
If I publish a property parser, then there will be releases too :)
Anyway, give me a week.

**Comment by phoerious** [comment]
How's the release coming along? :see_no_evil:

**Comment by lexborisov** [comment]
@phoerious 

Unfortunately, everything is dragging on. I rewrote not a small part of the CSS parser and this also affected the selectors.
I would love to make a release with these changes.

**Comment by phoerious** [comment]
What are the implications of the rewrite?

**Comment by lexborisov** [comment]
@phoerious 

Thanks for the report!
Fixed.
