### ISSUE TITLE
Print contents of one table element

### ISSUE THREAD

**Issue by patrick-luck** [lexbor/lexbor#144]
Hello,

I have been attempting to find a table element by its header, to then extract and print its raw data value from between the `<td></td>` tags. The line of HTML with the value of interest being 0.7 can be seen as follows:

`<td headers=\"choose-this-header\">0.7</td>`

Using the examples "elements_by_attr.c" and "text.c":
- With the first example, I have managed to find the table element by its header, but the desired value next to the tag (as well as the closing tag after that) are not printed out. The program outputs:

`<td headers="choose-this-header"> `
instead of:
`<td headers="choose-this-header">0.7</td>`

If I manually copy and paste the entire line of HTML representing table element and its inner value into example "text.c", the value is extracted and printed out as follows:

`HTML:`
`<td headers="choose-this-header">0.7</td>`
`Result:`
`0.7`

Does anyone know if there is an easier way to do this?

If not, I think I need to find a way to modify the first program to save the entire line into a buffer rather than the shorted version containing only the opening tag.

If anyone has a few moments and doesn't mind taking a look, I have included the full details and my code at the following SO link:

https://stackoverflow.com/questions/69827153/lexbor-webscraping-a-html-table-in-c

Thanks for making this project. Please let me know if I may be able to provide any more information about my question.

Patrick

**Comment by lexborisov** [comment]
Hi @patrick-luck 

I answered you two letters with this question.
Answered on StackOverflow.

**Comment by patrick-luck** [comment]
Hi @lexborisov 

Thank you for providing the example, I really appreciate it - I have upvoted and accepted your answer on StackOverflow.

Thanks again,

Patrick
