### ISSUE TITLE
Crash in CSS class selector when document contains empty class attributes

### ISSUE THREAD

**Issue by phoerious** [lexbor/lexbor#145]
CSS class selectors crash if the document contains HTML tags with empty-values class attributes.
 
Background: I tried to parse a website that turned out to be a text file filled with URLs in angle brackets, of which one contains the word `class`. The file looks a little like this:
```
... Lots of stuff here ...

<http://experiment.worldcat.org/entity/work/data/2865052259#Person/cicero_marcus_tullius> <http://schema.org/name> "Marcus Tullius Cicero" .
<http://dewey.info/class/937.05092/e21/> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Intangible> .
<http://experiment.worldcat.org/entity/work/data/2865052259#Topic/hommes_d_etat_rome> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Intangible> .
<http://experiment.worldcat.org/entity/work/data/2865052259#Topic/hommes_d_etat_rome> <http://schema.org/name> "Hommes d'État--Rome"@fr .

... Lots of more stuff here ...
```
This is not valid HTML, but it shouldn't crash. The crash happens because of this part:
```
<http://dewey.info/class/937.05092/e21/> 
```

The issue is reproducible also with valid HTML such as
```
<foo class>
```
No matter which class selector I use or whether it matches any element or not, I get a segfault with the following code:
```c
lxb_status_t css_cb(lxb_dom_node_t*, lxb_css_selector_specificity_t*, void*) {
    return LXB_STATUS_OK;
}

int main(void) {
    static const lxb_char_t html[] = "<http://dewey.info/class/937.05092/e21/> ";     // Crash
//    static const lxb_char_t html[] = "<foo class>";                                 // Crash
//    static const lxb_char_t html[] = "<foo class='bar'>";                           // Works

    lxb_html_document_t* html_document = lxb_html_document_create();
    lxb_html_document_parse(html_document, html, sizeof(html) - 1);
    lxb_dom_document_t* document = &html_document->dom_document;

    lxb_css_parser_t* css_parser = lxb_css_parser_create();
    lxb_css_parser_init(css_parser, NULL, NULL);

    lxb_css_selectors_t* css_selectors = lxb_css_selectors_create();
    lxb_css_selectors_init(css_selectors, 32);
    lxb_css_parser_selectors_set(css_parser, css_selectors);

    lxb_selectors_t* selectors = lxb_selectors_create();
    lxb_selectors_init(selectors);

    static const lxb_char_t selector[] = ".class-selector";
    lxb_css_selector_list_t* sel_list = lxb_css_selectors_parse(css_parser, selector, sizeof(selector) - 1);

    // SEGFAULT HERE
    lxb_selectors_find(selectors, lxb_dom_interface_node(document), sel_list, (lxb_selectors_cb_f)css_cb, NULL);

    return 0;
}
```

This may already be fixed with your CSS rework, but it is reproducible on the master branch at least.

**Comment by phoerious** [comment]
Any new on this or the release?

**Comment by phoerious** [comment]
Ping. Any idea what may be wrong? This literally prevents me from using an CSS class selectors whatsoever.

**Comment by lexborisov** [comment]
@phoerious 

A thousand apologies for not answering for a long time.
I will fix this bug in the near future.

Thanks for the report!

**Comment by phoerious** [comment]
I've had more crashes and they can all be traced back to this bug. The error isn't limited to CSS selectors, but can be reproduced with `lxb_dom_elements_by_class_name()` and, more generally, with `lxb_dom_elements_by_attr()` as well. Any null-valued attribute will crash Lexbor.

Here's a minimal Resiliparse example:
```python
from resiliparse.parse.html import HTMLTree

tree = HTMLTree.parse('<div role></div>')
print(tree.body.get_elements_by_attr('role', 'main'))
```
```
Process finished with exit code -1073741819 (0xC0000005)
```
Here's the internal implementation, which simply uses `lxb_dom_elements_by_attr()`: https://github.com/chatnoir-eu/chatnoir-resiliparse/blob/develop/resiliparse/resiliparse/parse/html.pyx#L231

**Comment by phoerious** [comment]
FYI: I have a PR in progress that will fix this issue.
