### ISSUE TITLE
Custom serialization 

### ISSUE THREAD

**Issue by noam3127** [lexbor/lexbor#146]
First of all, thank you for this great library!

I'm looking for a way to apply custom transformations to elements during serialization. Specifically, I need to convert the HTML to valid XML (e.g.- make all void elements have (self) closing tags, ensure all attributes are properly formatted, etc).

I don't see documentation for the [serialization](https://github.com/lexbor/lexbor/blob/master/source/lexbor/html/serialize.c) functions, and was wondering what the best way is to accomplish what I need.

**Comment by lexborisov** [comment]
@noam3127 

Serialization to [HTML specification](https://html.spec.whatwg.org/multipage/parsing.html#serialising-html-fragments).
You can see how the current serialization is implemented and create your own functions based on it.
Use [`lxb_html_node_is_void(...)`](https://github.com/lexbor/lexbor/blob/5ffe6e63270aa3ff79e5f53506a0ba63a945a3b2/source/lexbor/html/node.h#L22) to detect `void` elements.

**Comment by noam3127** [comment]
@lexborisov This looks like a bug [here](https://github.com/lexbor/lexbor/blob/master/source/lexbor/html/serialize.c#L741). The second argument should be `6`.

**Comment by lexborisov** [comment]
@lexborisov 

Yep, this is a bug `copy-paste`. 
I will fix it.

Thanks for the report[

**Comment by lexborisov** [comment]
@noam3127 

Oh God how could I forget about that.
Thanks for the report.
