### ISSUE TITLE
Exception: SegFault in lexbor_core_hash for x86, armv7 and armhf

### ISSUE THREAD

**Issue by txgk** [lexbor/lexbor#153]
Hi, today I tried to package lexbor for Alpine Linux repository and stumbled across a bug in tests for x86, armv7 and armhf architectures.

In build logs for these architectures only one test fails - `lexbor_core_hash`. Here's a faulty line:

```
7/97 Test  #7: lexbor_core_hash ........................***Exception: SegFault  0.00 sec
```

https://gitlab.alpinelinux.org/grikir02/aports/-/pipelines/110534

[armhf-log.txt](https://github.com/lexbor/lexbor/files/8049034/armhf-log.txt)

[armv7-log.txt](https://github.com/lexbor/lexbor/files/8049035/armv7-log.txt)

[x86-log.txt](https://github.com/lexbor/lexbor/files/8049036/x86-log.txt)

**Comment by vtorri** [comment]
First
CFLAGS: -Os -fomit-frame-pointer -O2 -Wall -pedantic -pipe -std=c99 -fPIC
CXXFLAGS: -Os -fomit-frame-pointer -O2 

-Os and -O2 : too much -O
-s removes the debug symbols
-fomit-frame-pointer removes the debug frames too

to have useful backtrace when there is a seg fault : 

for CFLAGS: -g3 -ggdb3 -O2 -Wall -pedantic -pipe -std=c99 -fPIC
for CXXFLAGS : -g3 -ggdb3 -O2 -Wall -pedantic -pipe -fPIC

Vincent

**Comment by txgk** [comment]
Unfortunately I don't have a 32-bit machine to analyze this test in more details. I hope the problem can be identified without deep debugging.

**Comment by psycholance** [comment]
> -Os and -O2 : too much -O
> -s removes the debug symbols

-Os does not remove debug symbols, (and in this case they are never generated because there is no -g), and only the last -O option is the one that takes effect, so this is just compiled with -O2  
-fomit-frame-pointer is also the default on most platforms (though i don't recall whether it is on by default on these arches, but probably not the default on the arm* ones)  
but yes, should do some testing with debug symbols- x86 can be emulated on x86_64 at least

**Comment by lexborisov** [comment]
@txgk 

Thanks for the report! I will fix this after commit css styles.

**Comment by ptrcnull** [comment]
Hi, here's the full backtrace:
```
#0  lexbor_hash_entry_str (entry=0x79656b)
    at /root/aports/testing/lexbor/src/lexbor-2.1.0/source/lexbor/core/hash.h:163
No locals.
#1  lexbor_hash_search_by_hash_id (hash=0xffcb5ef8, hash_id=3804703177, key=0x56580060 "KeY", 
    length=3, cmp_func=0xf7bd6d40 <lexbor_str_data_ncmp>)
    at /root/aports/testing/lexbor/src/lexbor-2.1.0/source/lexbor/core/hash.c:330
        str = <optimized out>
        entry = 0x79656b
#2  0xf7bd4906 in lexbor_hash_search (hash=0xffcb5ef8, 
    search=0xf7eecc70 <lexbor_hash_search_var>, key=0x56580060 "KeY", length=3)
    at /root/aports/testing/lexbor/src/lexbor-2.1.0/source/lexbor/core/hash.c:277
No locals.
#3  0x5657ecbc in insert_search_case (my_test=0xf7f9bd80)
    at /root/aports/testing/lexbor/src/lexbor-2.1.0/test/lexbor/core/hash.c:117
        hash = {entries = 0xf7f9bf00, mraw = 0x56582e20, table = 0xf7b16b60, table_size = 1024, 
          struct_size = 24}
        status = <optimized out>
        entry_raw = 0xf7b051d0
        entry_lo = 0xf7b051e8
        entry_up = 0xf7b05200
        entry = <optimized out>
        return_val = 0x0
        __func__ = "insert_search_case"
#4  0xf7ef72f3 in test_run (test=0xf7f9bd80, name=0x565800f5 "lexbor/core/hash")
    at /root/aports/testing/lexbor/src/lexbor-2.1.0/test/unit/test.c:114
        i = 6
        bad_tmp = 0
        entry = 0xf7b0d060
        list = 0x56582c70
#5  0x5657e345 in main (argc=1, argv=0xffcb6034)
    at /root/aports/testing/lexbor/src/lexbor-2.1.0/test/lexbor/core/hash.c:167
        my_test = 0xf7f9bd80
```
