### ISSUE TITLE
Information about lexbor.com

### ISSUE THREAD

**Issue by lexborisov** [lexbor/lexbor#158]
The lexbor.com server not only as a page shower, but also as a testing platform for the lexbor project. There kvm with many operating systems on which the code is tested/packages.

Unfortunately, due to economic sanctions, I can't transfer money to pay for the server in hetzner.

I will look for options. Perhaps the site will have to be closed, testing transferred to a local computer.
In general, it is not yet clear what will happen.

In any case, this issue will be resolved without compromising the quality of the code.

So it goes.

**Comment by vtorri** [comment]
Github allows to execute actions, so maybe you can transfer your tests to github. Maybe there are not as many OS as in your kwm, but at least, you can test on linux, windows, mac and freebsd (even Solaris !). That could be a temporary solution

**Comment by lexborisov** [comment]
@vtorri 

Yes, I know about it, but it's just a castrated solution.

**Comment by vtorri** [comment]
@lexborisov it is better than nothing. And temporary until a better solution

**Comment by vtorri** [comment]
tell me if you want some help
