### ISSUE TITLE
Memory leak of elements

### ISSUE THREAD

**Issue by keto33** [lexbor/lexbor#160]
I parsed documents fetched from the MySQL database in a loop. I was unable to free the memory allocated for `element`.

```
    while ((row = mysql_fetch_row(result)))
    {
        document = lxb_html_document_create();
        if (document == NULL)
        {
            FAILED("Failed to create HTML Document");
        }
        lxb_char_t html[strlen(row[1]) + 1];
        strcpy(html, row[1]);
        size_t html_len = sizeof(html) - 1;

        status = lxb_html_document_parse(document, html, html_len);
        if (status != LXB_STATUS_OK)
        {
            FAILED("Failed to parse HTML");
        }

        collection = lxb_dom_collection_make(&document->dom_document, 128);
        if (collection == NULL)
        {
            FAILED("Failed to create Collection object");
        }
        status = lxb_dom_elements_by_tag_name(lxb_dom_interface_element(document->body), collection, 
            (const lxb_char_t *)"h1", 2);
        if (status != LXB_STATUS_OK)
        {
            puts("Failed to get elements by name");
        }

        if (lxb_dom_collection_length(collection) > 0)
        {
            element = lxb_dom_collection_element(collection, 0);
        }
        lxb_dom_element_destroy(element);
        lxb_dom_element_interface_destroy(element);
        lxb_dom_collection_destroy(collection, true);
        lxb_html_document_destroy(document);
    }
```

There was no memory leak without the line `element = lxb_dom_collection_element(collection, 0);`. Isn't it the job of `lxb_dom_element_destroy(element);` to do so?

**Comment by lexborisov** [comment]
Hi @keto33 

1.
There are no memory leaks in the code you provided, but there is double freeing.

```C
lxb_dom_element_destroy(element);                     /* first element destruction */
lxb_dom_element_interface_destroy(element);    /* use-after-poison */
lxb_dom_collection_destroy(collection, true);
lxb_html_document_destroy(document);
```

Remove `lxb_dom_element_interface_destroy(element);` and everything will be fine.

2.
Also, I don't understand the point of destroying an element.
You destroy an element without removing it from the tree. The tree will contain pointers to the already freed memory.

For remove element from the tree use function `lxb_dom_node_remove(lxb_dom_node_t *node)`:
```C
lxb_dom_node_remove(lxb_dom_interface_node(element));
```
and then you can destroy the element:
```C
lxb_dom_element_destroy(element);
```

3.
Also in the above code you have a gross error.
If there are no elements in the collection, then you will try to free the garbage.
This will cause the program to crash.

```C
        if (lxb_dom_collection_length(collection) > 0)
        {
            element = lxb_dom_collection_element(collection, 0);
        }
        lxb_dom_element_destroy(element);
```

As a result.

I would do like this:

```C
    while ((row = mysql_fetch_row(result)))
    {
        document = lxb_html_document_create();
        if (document == NULL)
        {
            FAILED("Failed to create HTML Document");
        }
        lxb_char_t html[strlen(row[1]) + 1];
        strcpy(html, row[1]);
        size_t html_len = sizeof(html) - 1;

        status = lxb_html_document_parse(document, html, html_len);
        if (status != LXB_STATUS_OK)
        {
            FAILED("Failed to parse HTML");
        }

        collection = lxb_dom_collection_make(&document->dom_document, 128);
        if (collection == NULL)
        {
            FAILED("Failed to create Collection object");
        }
        status = lxb_dom_elements_by_tag_name(lxb_dom_interface_element(document->body), collection, 
            (const lxb_char_t *)"h1", 2);
        if (status != LXB_STATUS_OK)
        {
            puts("Failed to get elements by name");
        }

        if (lxb_dom_collection_length(collection) > 0)
        {
            element = lxb_dom_collection_element(collection, 0);

            /* Do something? */

            /* lexbor_str_t str = {.data = NULL};
            status = lxb_html_serialize_str(lxb_dom_interface_node(element), &str); */
        }

        lxb_dom_collection_destroy(collection, true);
        lxb_html_document_destroy(document);
    }
```

**Comment by vtorri** [comment]
there should some link in the doc (like the @see doxygen tag), to reference similar functions, to know which function should be used

**Comment by lexborisov** [comment]
@vtorri 
Yes, there is a problem with the documentation. Let's try to solve it.

**Comment by keto33** [comment]
I started with the code you suggested. Memory usage constantly increases. This is the reason I tried all possible methods to free the memory consumed by `element`.

remove the `element` line, then there is no change in the memory usage throughout the link.

    while ((row = mysql_fetch_row(result)))
    {
        document = lxb_html_document_create();
        if (document == NULL)
        {
            FAILED("Failed to create HTML Document");
        }
        lxb_char_t html[strlen(row[1]) + 1];
        strcpy(html, row[1]);
        size_t html_len = sizeof(html) - 1;

        status = lxb_html_document_parse(document, html, html_len);
        if (status != LXB_STATUS_OK)
        {
            FAILED("Failed to parse HTML");
        }

        collection = lxb_dom_collection_make(&document->dom_document, 128);
        if (collection == NULL)
        {
            FAILED("Failed to create Collection object");
        }
        status = lxb_dom_elements_by_tag_name(lxb_dom_interface_element(document->body), collection, 
            (const lxb_char_t *)"h1", 2);
        if (status != LXB_STATUS_OK)
        {
            puts("Failed to get elements by name");
        }

        if (lxb_dom_collection_length(collection) > 0)
        {
            // element = lxb_dom_collection_element(collection, 0);

        }

        lxb_dom_collection_destroy(collection, true);
        lxb_html_document_destroy(document);
    }

The memory allocated to `element` is not freed by destroying `collection` and `document`.

**Comment by lexborisov** [comment]
@keto33 

> The memory allocated to element is not freed by destroying collection and document.

Why do you think so?
During document destruction, all used memory is freed.

**Comment by lexborisov** [comment]
@keto33 

What version of the library are you using?

**Comment by keto33** [comment]
I am truly sorry. It was all my mistake.

In the testing code, I had `if(lxb_dom_collection_length(collection)==0){continue;}` (I don't know how I came up with this stupid idea). Skipping the loop avoided executing `lxb_dom_collection_destroy(collection, true); lxb_html_document_destroy(document);`.

I am so sorry!
