### ISSUE TITLE
HTML tree serialization shows extra quotation marks

### ISSUE THREAD

**Issue by Tectu** [lexbor/lexbor#162]
I'm using the built in `lxb_html_serialize_pretty_tree_str()` function to serialize/print an HTML DOM to a string.
The output is pretty much matching expectations. However, text nodes seem to be printed with extra quotation marks surrounding the text.
For example, serializing the following DOM using `lxb_html_serialize_pretty_tree_str()`:
```html
<html><body><h1>Title</h1></body></html>
```
will produce this output:
```html
<html>
  <head>
  </head>
  <body>
    <h1>
      "Title"
    </h1>
  </body>
</html>
```
Where do these quotations marks come from? How does one get rid of them?
While here, the same question applies to the extra newlines. One would expect to get `<h1>Title</h1>` (the entire element in one line but instead it contains extra whitespaces.

I've looked a bit through the source code, especially the various serialization options but didn't spot anything which would be directly related to the quotation marks and extra newlines.

**Comment by lexborisov** [comment]
Hi @Tectu 

In this case, pretty is the human readable format. It cannot be reused for parsing in any way.
Please, use `lxb_html_serialize_tree_cb`, `lxb_html_serialize_tree_str`, `lxb_html_serialize_deep_cb`, or `lxb_html_serialize_deep_str` to output according to the specification.

**Comment by Tectu** [comment]
Hey,

Thanks a lot for the super fast reply! :)

Indeed, using `lxb_html_serialize_tree_str()` produces the output expected for my use case.
I guess this is just another installment of #159 (missing API documentation) :D

Thank you for your great work with this library and your fast support. It's greatly appreciated!
