### ISSUE TITLE
Missing to select nodes in <template>

### ISSUE THREAD

**Issue by zyc9012** [lexbor/lexbor#170]
The nodes in `<template>` tags will not be searched when `lxb_selectors_find`. For example:
```
<div>
</div>
<template>
  <div>
  </div>
</template>
```

When finding all `div`s, only the outer `div` will be returned.

**Comment by lexborisov** [comment]
@zyc9012 

That's right. Searches within templates should not be performed.
Template tag has no children. All children of the template element are in the content parameter.
Please read how the template element works in html.

See [template lement](https://github.com/lexbor/lexbor/blob/master/source/lexbor/html/interfaces/template_element.h#L23).
See [template serialize](https://github.com/lexbor/lexbor/blob/master/source/lexbor/html/serialize.c#L258)

**Comment by zyc9012** [comment]
I see, thanks for the explanation.
