### ISSUE TITLE
wrong link in css property wiki ?

### ISSUE THREAD

**Issue by vtorri** [lexbor/lexbor#173]
in the CSS property wiki, there is the link

https://drafts.csswg.org/css-display-3/#the-display-properties

but for me, it's a link to an unknown page of https://drafts.csswg.org

**Comment by vtorri** [comment]
same here : http://lexbor.com/docs/lexbor/#css

**Comment by lexborisov** [comment]
@vtorri 

All links are working correctly.

**Comment by vtorri** [comment]
when i click on it, either the site saying the doc is not found, and this morning, see img attached:

![css_org](https://user-images.githubusercontent.com/1422401/217465877-7b89919d-fbd5-48bf-884d-35b68e7de196.png)

**Comment by vtorri** [comment]
either at home, or at work

**Comment by vtorri** [comment]
and now working... maybe some problems at w3c
