### ISSUE TITLE
SAX and DOM

### ISSUE THREAD

**Issue by seven1995** [lexbor/lexbor#175]
hello! is that library support to parse HTML based on SAX and DOM? thank for your answer！

**Comment by lexborisov** [comment]
@seven1995 

> on SAX

There is no [SAX](https://en.wikipedia.org/wiki/Simple_API_for_XML) in the literal sense. You can use tokenizer for stream parsing. Please, look at an [example](https://github.com/lexbor/lexbor/blob/master/examples/lexbor/html/tokenizer/simple.c).
That is, the token will contain all the information about the tag or attribute. It is worth noting that the token is always the same. They are not created for every tag/element. 

> and DOM

All created elements (HTML/SVG/MathML) are based on the DOM. [Look at interfaces in DOM](https://github.com/lexbor/lexbor/tree/master/source/lexbor/dom/interfaces) and [HTML](https://github.com/lexbor/lexbor/tree/master/source/lexbor/html/interfaces).
