### ISSUE TITLE
list of CSS properties to implement

### ISSUE THREAD

**Issue by vtorri** [lexbor/lexbor#177]
Hello

have you listed the CSS  properties that you want to implement ?

**Comment by lexborisov** [comment]
Hi @vtorri 

Yes, it is a permanent task to add support for new CSS properties.

Moving on.
The plan is this:
1. Figure out the Font.
2. Implement the layout for the GUI. Under GPL3.

That is, I'm moving in the same direction. Create an engine that can be used for different things.

In other words, a framework for developing cross-platform software in C programming language.

**Comment by vtorri** [comment]
I can't remember if i told you but I plan to use lexbor for epub (version 2 and 3) and chm help files.

**Comment by lexborisov** [comment]
@vtorri 

Yes, I remember, I think you won't have a problem using my code.
