### ISSUE TITLE
Undefined reference

### ISSUE THREAD

**Issue by MasterSoft24** [lexbor/lexbor#19]
Я пробую собрать, скопировав пример из Quick Start https://lexbor.com/docs/lexbor/
но при сборке получаю 
```
 undefined reference to `lxb_html_document_create'
undefined reference to `lxb_html_document_parse'
undefined reference to `lxb_html_document_destroy'
```

платформа linux. IDE NetBeans. С ctandart с11

IDE выдает придупреждение на импорт  <lexbor/html/parser.h> - 

> существует неразрешенный #include <stddef.h> во включенном элементе /usr/include/stdio.h

**Comment by lexborisov** [comment]
Привет!

Вы собираете сами? То есть, не CMake?
Если сами, то посмотрите, точно ли создаются объекты в lexbor/html/interfaces/ и включаются ли они в вашу программу.

На счёт предупреждения `С ctandart с11` посмотрю сегодня.

**Comment by lexborisov** [comment]
@MasterSoft24 
Лучше, конечно, использовать CMake для [сборки библиотеки](https://lexbor.com/docs/lexbor/#linux___bsd__mac_os_x).

**Comment by vtorri** [comment]
it would be nice if you could write in english...

**Comment by MasterSoft24** [comment]
I create two separate projects in Netbeans IDE. First is a lexbor and second is an application whos used lexbor as a dynamic library.  Lexbor project compilation is going normally. In the second project, I'm past code from the Quickstart and a described error appears during compilation of it.
Maybe I'm including a wrong header file for this purpose?

```
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <lexbor/html/parser.h>

/*
 * 
 */
int main(int argc, char** argv) {

 lxb_status_t status;
    const lxb_char_t *tag_name;
    lxb_html_document_t *document;

    static const lxb_char_t html[] = "<div>Work fine!</div>";
    size_t html_len = sizeof(html) - 1;

    document = lxb_html_document_create();
    if (document == NULL) {
        exit(EXIT_FAILURE);
    }

    status = lxb_html_document_parse(document, html, html_len);
    if (status != LXB_STATUS_OK) {
        exit(EXIT_FAILURE);
    }

    tag_name = lxb_tag_name_by_id(lxb_html_document_tag_heap(document),
                                  lxb_dom_interface_node(document->body)->tag_id, NULL);

    printf("Element tag name: %s\n", tag_name);

    lxb_html_document_destroy(document);

    return EXIT_SUCCESS;
}
```

**Comment by vtorri** [comment]
you should have pkg-config. confiogure you project to use lexbor : 
cflags : pkg-config --cflags lexbor
ldflags (linker) : pkg-config --libs lexbor

**Comment by lexborisov** [comment]
@MasterSoft24 
I do not know how Netbeans IDE works. You need to somehow connect the object file or library to your other project.
This is a question to know Netbeans IDE, not lexbor.

**Comment by MasterSoft24** [comment]
Ok, thank you

**Comment by mengyingzhou** [comment]
@lexborisov 

Hi, I have met the same problem with the ``configure`` file. And I have added the CFLAGS and LDFLAGS to ``configure`` just like the way in this [link](https://unix.stackexchange.com/questions/149359/what-is-the-correct-syntax-to-add-cflags-and-ldflags-to-configure): 

```shell
./configure PKG_CONFIG_PATH=$PWD/../../openssl/build/lib/pkgconfig CFLAGS="-I$PWD/../../lexbor" LDFLAGS="-Wl,-rpath,$PWD/../../openssl/build/lib,-L$PWD/../../lexbor"
```

But it still shows the error.

the error is listed below:
``` shell
client.o: In function `(anonymous namespace)::message_complete_cb(http_parser*)':
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:442: undefined reference to `lxb_html_document_create'
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:447: undefined reference to `lxb_html_document_parse'
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:453: undefined reference to `lxb_dom_collection_create'
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:454: undefined reference to `lxb_dom_collection_init'
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:460: undefined reference to `lxb_dom_elements_by_attr_begin'
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:467: undefined reference to `lxb_dom_element_attr_by_name'
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:479: undefined reference to `lxb_html_document_destroy'
```

I use Ubuntu 18.04. 
I have tried to install the library both from Binary packages and source code. Neither doesn't work.

Thanks for your help!

Best, 
Mengying
