### ISSUE TITLE
严重漏洞

### ISSUE THREAD

**Issue by paul91clinelogs23** [lexbor/lexbor#195]
lxb_dom_element_set_attribute(element,(const lxb_char_t *) "id", 2,(const lxb_char_t *) value.c_str(), value.length()); // 执行此命令后整个element将变成LXB_DOM_NODE_TYPE_ATTRIBUTE，导致整个element序列化为空，将element插入DOM树后会导致破坏整个树结构。导致空指针报错。

**Comment by paul91clinelogs23** [comment]
I hope the expert (or guru) can fix it soon.

**Comment by lexborisov** [comment]
Hi @paul91clinelogs23 

I tried to reproduce the error:
```C
lxb_dom_attr_t *attr;
lxb_dom_element_t *element;

element = lxb_dom_interface_element(document->head);

attr = lxb_dom_element_set_attribute(element, "id", 2, "lala", 4);

lxb_html_serialize_deep_cb(lxb_dom_interface_node(document), callback, NULL);
```

Work fine.

`element->node.type == LXB_DOM_NODE_TYPE_ELEMENT`
`attr->node.type == LXB_DOM_NODE_TYPE_ATTRIBUTE`

Need some details. Full code example, HTML example where this happens.

**Comment by paul91clinelogs23** [comment]
请使用lxb_dom_document_create_element命令新建一个element，此时这个element并未在DOM树中，请经过lxb_dom_element_set_attribute(element, "id", 2, "lala", 4);后，再插入到DOM树中，再序列化，就会发现序列化后的HTML会发生问题，并且element再未插入之前序列化，也不会显示正确的html标签代码，请注意我创建的是form标签

**Comment by paul91clinelogs23** [comment]
"Please use the lxb_dom_document_create_element command to create a new element. At this point, this element is not in the DOM tree. After executing lxb_dom_element_set_attribute(element, "id", 2, "lala", 4);, insert it into the DOM tree. Then, when serialized, you will find issues with the serialized HTML. Also, if you serialize the element before inserting it, it won't display the correct HTML tag code. Please note that the tag I created is a 'form' tag."

**Comment by paul91clinelogs23** [comment]
执行前：![image](https://github.com/lexbor/lexbor/assets/143726696/fbadd470-b831-4889-88b4-0a62a7f3792f)
执行后：
![image](https://github.com/lexbor/lexbor/assets/143726696/0daa5163-813d-443e-b552-063cab866673)
它甚至将我的user都清空了。

**Comment by paul91clinelogs23** [comment]
可以发现的是，element内存地址没有发生变化，但是里面的结构已经被覆盖成新的数据。

**Comment by lexborisov** [comment]
@paul91clinelogs23 

What function do you use to insert an item into the tree?

**Comment by paul91clinelogs23** [comment]
lxb_dom_node_insert_child

**Comment by paul91clinelogs23** [comment]
> @paul91clinelogs23
> 
> What function do you use to insert an element into the tree?

lxb_dom_node_insert_child

**Comment by paul91clinelogs23** [comment]
我认为bug出现的原因是因为执行lxb_dom_element_set_attribute(element, "id", 2, "lala", 4);后，里面的结构已经被覆盖成新的数据

**Comment by paul91clinelogs23** [comment]
好像这个漏洞只有创建form时会发生。

**Comment by lexborisov** [comment]
@paul91clinelogs23 

Here's an example I'm using. It works. Is there any way you can do it differently? Please compare.

```C
#include <lexbor/html/html.h>


lxb_status_t
callback(const lxb_char_t *data, size_t len, void *ctx)
{
    printf("%.*s", (int) len, (char *) data);
    return LXB_STATUS_OK;
}

int
main(int argc, const char *argv[])
{
    lxb_status_t status;
    lxb_dom_attr_t *attr;
    lxb_dom_element_t *element;
    lxb_html_document_t *document;

    static const lexbor_str_t html = lexbor_str("<div>test</div>");
    static const lexbor_str_t form = lexbor_str("form");
    static const lexbor_str_t name = lexbor_str("id");
    static const lexbor_str_t value = lexbor_str("lala");

    document = lxb_html_document_create();
    if (document == NULL) {
        return EXIT_FAILURE;
    }

    status = lxb_html_document_parse(document, html.data, html.length);
    if (status != LXB_STATUS_OK) {
        return EXIT_FAILURE;
    }

    element = lxb_dom_document_create_element(lxb_dom_interface_document(document),
                                              form.data, form.length, NULL);
    if (element == NULL) {
        return EXIT_FAILURE;
    }

    attr = lxb_dom_element_set_attribute(element, name.data, name.length,
                                         value.data, value.length);
    if (attr == NULL) {
        return EXIT_FAILURE;
    }

    lxb_dom_node_insert_child(lxb_dom_interface_node(document->body),
                              lxb_dom_interface_node(element));

    lxb_html_serialize_deep_cb(lxb_dom_interface_node(document), callback, NULL);

    lxb_html_document_destroy(document);

    printf("\nDone\n");

    return EXIT_SUCCESS;
}

```

Result:
```
<html><head></head><body><div>test</div><form id="lala"></form></body></html>
Done
```

**Comment by paul91clinelogs23** [comment]
稍等，我试试

> @paul91clinelogs23
> 
> 这是我正在使用的一个例子。它有效。有什么方法可以做不同的事情吗？请比较。
> 
> ```c
> #include <lexbor/html/html.h>
> 
> 
> lxb_status_t
> callback(const lxb_char_t *data, size_t len, void *ctx)
> {
>     printf("%.*s", (int) len, (char *) data);
>     return LXB_STATUS_OK;
> }
> 
> int
> main(int argc, const char *argv[])
> {
>     lxb_status_t status;
>     lxb_dom_attr_t *attr;
>     lxb_dom_element_t *element;
>     lxb_html_document_t *document;
> 
>     static const lexbor_str_t html = lexbor_str("<div>test</div>");
>     static const lexbor_str_t form = lexbor_str("form");
>     static const lexbor_str_t name = lexbor_str("id");
>     static const lexbor_str_t value = lexbor_str("lala");
> 
>     document = lxb_html_document_create();
>     if (document == NULL) {
>         return EXIT_FAILURE;
>     }
> 
>     status = lxb_html_document_parse(document, html.data, html.length);
>     if (status != LXB_STATUS_OK) {
>         return EXIT_FAILURE;
>     }
> 
>     element = lxb_dom_document_create_element(lxb_dom_interface_document(document),
>                                               form.data, form.length, NULL);
>     if (element == NULL) {
>         return EXIT_FAILURE;
>     }
> 
>     attr = lxb_dom_element_set_attribute(element, name.data, name.length,
>                                          value.data, value.length);
>     if (attr == NULL) {
>         return EXIT_FAILURE;
>     }
> 
>     lxb_dom_node_insert_child(lxb_dom_interface_node(document->body),
>                               lxb_dom_interface_node(element));
> 
>     lxb_html_serialize_deep_cb(lxb_dom_interface_node(document), callback, NULL);
> 
>     lxb_html_document_destroy(document);
> 
>     printf("\nDone\n");
> 
>     return EXIT_SUCCESS;
> }
> ```
> 
> 结果：
> 
> ```
> <html><head></head><body><div>test</div><form id="lala"></form></body></html>
> Done
> ```

稍等，我试试

**Comment by paul91clinelogs23** [comment]
此问题还是存在，通过测试，导致此情况发生的函数为
![image](https://github.com/lexbor/lexbor/assets/143726696/e4b7bc58-f315-49a8-9238-f17417fa9c1e)
从此函数执行完毕后，element的node.type就发生变化了，我现在是这么来处理该问题的
![image](https://github.com/lexbor/lexbor/assets/143726696/2a9e6421-4081-43ce-8390-77e166ddd02b)
检测一下创建完该element后，是否会出现问题，如果会出现问题就重新创建一个，销毁上一个。

**Comment by paul91clinelogs23** [comment]
我的开发环境是 window 10、CLion 2023.2、c++17，vs2022工具链

**Comment by lexborisov** [comment]
@paul91clinelogs23 

The example I gave you, does it reproduce the problem or not?
I mean, just compile my example in C and run it.

I've tested (above example) on Windows, Linux (with `-fsanitize=address` and `-fsanitize= memory`), macOS and it works fine everywhere.

**Comment by paul91clinelogs23** [comment]
该睡觉了，明天在研究。玄学的一个问题。

**Comment by lexborisov** [comment]
@paul91clinelogs23 

> 你提供的例子没有任何问题，但是在我的项目中出现了这个问题，我是将lexbor编译为静态库引入到我的项目中的。

There is something you are doing wrong. That is, somehow you've managed to corrupt the element's memory. Most likely the error is somewhere earlier.
It is a pity that we cannot see your code, those fragments where you use lexbor.

I'd really like to get to the bottom of this issue.

**Comment by paul91clinelogs23** [comment]
> @paul91clinelogs23
> 
> > 你提供的例子没有任何问题，但是在我的项目中出现了这个问题，我是将lexbor编译为静态库引入到我的项目中的。
> 
> There is something you are doing wrong. That is, somehow you've managed to corrupt the element's memory. Most likely the error is somewhere earlier. It is a pity that we cannot see your code, those fragments where you use lexbor.
> 
> I'd really like to get to the bottom of this issue.

您有微信或者聊天软件吗，我将更多的细节发送给您。

**Comment by paul91clinelogs23** [comment]
> @paul91clinelogs23
> 
> > 你提供的例子没有任何问题，但是在我的项目中出现了这个问题，我是将lexbor编译为静态库引入到我的项目中的。
> 
> There is something you are doing wrong. That is, somehow you've managed to corrupt the element's memory. Most likely the error is somewhere earlier. It is a pity that we cannot see your code, those fragments where you use lexbor.
> 
> I'd really like to get to the bottom of this issue.

I am willing to pay to solve this problem.

**Comment by paul91clinelogs23** [comment]
> @paul91clinelogs23
> 
> > 你提供的例子没有任何问题，但是在我的项目中出现了这个问题，我是将lexbor编译为静态库引入到我的项目中的。
> 
> There is something you are doing wrong. That is, somehow you've managed to corrupt the element's memory. Most likely the error is somewhere earlier. It is a pity that we cannot see your code, those fragments where you use lexbor.
> 
> I'd really like to get to the bottom of this issue.

I would be open to compensating for a solution to this issue.

**Comment by paul91clinelogs23** [comment]
还在吗

**Comment by lexborisov** [comment]
@paul91clinelogs23 

> 还在吗

I replied to your letter.
