### ISSUE TITLE
Get text from elements using tags

### ISSUE THREAD

**Issue by Chrd26** [lexbor/lexbor#196]
Hello! I have been using tags to get the text from elements [. I used this example](https://github.com/lexbor/lexbor/blob/0c4010b10a922a45513d67beec0ddd29c2951f85/examples/lexbor/html/elements_by_tag_name.c) but I am only getting \<p> printed out instead of the whole thing which means from \<p> to \</p>. 

Can you please provide me with an example or help me understand how I can achieve such a thing?

This is my code:

```cpp
    cpr::Response getRes = request_info(input);

    lxb_status_t status;
    lxb_dom_element_t* elem = nullptr;
    lxb_html_document_t* document = nullptr;
    lxb_dom_collection_t* collection = nullptr;

    lxb_char_t html[getRes.text.length() + 1];
    std::memset(html, 0, getRes.text.length() + 1);

    for (int i = 0; i < getRes.text.length(); i++) {
        html[i] = getRes.text[i];
    }


    size_t html_len = sizeof(html) - 1;

    document = Parse(html, html_len);
    collection = lxb_dom_collection_make(&document->dom_document, 128);

    if (collection == nullptr)
    {
        exit(EXIT_FAILURE);
    }

    // Get status of creating a collection of elements that use the paragraph tag
    status = lxb_dom_elements_by_tag_name(lxb_dom_interface_element(document->body),
                                          collection, (const lxb_char_t*) "p", 1);

    if (status != LXB_STATUS_OK)
    {
        exit(EXIT_FAILURE);
    }


    for (size_t i = 0; i < lxb_dom_collection_length(collection); i++)
    {
        elem = lxb_dom_collection_element(collection, i);
        serialize_node(lxb_dom_interface_node(elem));
    }

    lxb_dom_collection_destroy(collection, true);
    lxb_html_document_destroy(document);
```

Thank you for your time!

**Comment by lexborisov** [comment]
@Chrd26 

To retrieve text from an element, you can do the following:

1. Use [lxb_dom_node_text_content()`](https://github.com/lexbor/lexbor/blob/0c4010b10a922a45513d67beec0ddd29c2951f85/source/lexbor/dom/interfaces/node.h#L117) function. But the function allocates memory and reassembles all the text into one whole, even from nested tags.
2. Use [lxb_dom_node_simple_walk()](https://github.com/lexbor/lexbor/blob/0c4010b10a922a45513d67beec0ddd29c2951f85/source/lexbor/dom/interfaces/node.h#L108) function. In the callback, you select only the `LXB_TAG__TEXT` text nodes. `lxb_dom_interface_node(elem)->local_name == LXB_TAG__TEXT`.
3. Take a text node by hand.

```C
lxb_dom_node_t *node;
lxb_dom_character_data_t *ch_data;

node = lxb_dom_interface_node(elem)->first_child;

if (node != NULL && node->local_name == LXB_TAG__TEXT) {
    ch_data = lxb_dom_character_data_interface(node);

    printf("%.*s\n", (int) ch_data->data.length, (const char *) ch_data->data.data);
}
```

**Comment by Chrd26** [comment]
Perfect! Thank you for your swift answer! I get the proper content now.
