### ISSUE TITLE
Build fail if g++ is not installed

### ISSUE THREAD

**Issue by trikko** [lexbor/lexbor#197]
On a simple docker with gcc but not g++ installed, lexbor does not build. CMake fails, but it shouldn't. If I'm right, lexbor doesn't need a c++ compiler. This force extra installation of c++ build tools.

**Comment by lexborisov** [comment]
@trikko 

I have C++ turned on for one test.
Okay, I do this: by default, LEXBOR_BUILD_TESTS_CPP will be OFF, and the C++ compiler will only be included if LEXBOR_BUILD_TESTS_CPP=ON.
Now the C++ compiler is enabled regardless of the values passed in.

**Comment by lexborisov** [comment]
@trikko 

Fixed in https://github.com/lexbor/lexbor/commit/14166847cfa85d80c9041f5387014961f70f3831.
Thanks for the report!

**Comment by trikko** [comment]
yay it works!
