### ISSUE TITLE
lxb_dom_node_text_content_set not decode entities

### ISSUE THREAD

**Issue by kostya** [lexbor/lexbor#198]
i try to change text of LXB_TAG__TEXT node:
`lxb_dom_node_text_content_set(..., "&#61 &amp; &Auml", ...)`
than 
`lxb_dom_node_text_content`
returns `"&#61 &amp; &Auml"`

is this expected or bug?

**Comment by lexborisov** [comment]
Hi @kostya 

Implemented to specification (see "The [textContent](https://dom.spec.whatwg.org/#dom-node-textcontent) setter"). According to the specification, the behavior is correct.

Browsers do the same.

```HTML
<div id="ididid">to</div>

<script>
	document.getElementById("ididid").textContent = "&#61 &amp; &Auml"
</script>
```

Result:
```
&#61 &amp; &Auml
```

**Comment by kostya** [comment]
ok. thanks.
