### ISSUE TITLE
How to get inner HTML of the element?

### ISSUE THREAD

**Issue by ivan-ushakov** [lexbor/lexbor#199]
Function `lxb_dom_node_text_content()` serializes HTML elements and produces only text. For example, removes BR elements. How to get element's content as inner HTML?

**Comment by lexborisov** [comment]
Hi @ivan-ushakov 

You can try [`lxb_html_serialize_*`](https://github.com/lexbor/lexbor/blob/master/source/lexbor/html/serialize.h#L46) functions.
