### ISSUE TITLE
Incorrect code in function lxb_html_get_attribute, source/lexbor/html/encoding.c

### ISSUE THREAD

**Issue by melkorb** [lexbor/lexbor#201]
source/lexbor/html/encoding.c, 480
```
spaces_state:

    data = lxb_html_encoding_skip_spaces(data, end);
    if (data == end) {
        return data;
    }

    if (*data != '=') {
        return data;
    }

value_state:

    data = lxb_html_encoding_skip_spaces(data, end);
```
At line 487 must be:
```
if (*data++ != '=') {
        return data;
}
```
if postincrement missed next 'lxb_html_encoding_skip_spaces' can not skip spaces after '='

**Comment by lexborisov** [comment]
@melkorb 

Thanks for the report!
Fixed in https://github.com/lexbor/lexbor/commit/2b87b4ccbaa970b46486f28a3f77d576904ece38.
