### ISSUE TITLE
cannot parse css selector without whitespace: + ~

### ISSUE THREAD

**Issue by iacore** [lexbor/lexbor#209]
Found with [selectolax](https://github.com/rushter/selectolax). I assume this is a lexbor bug.

```python
from selectolax.parser import HTMLParser
tree = HTMLParser("")
tree.css_first('dt')
tree.css_first('dt~dt') # error
tree.css_first('dt+dt') # error
```

**Comment by lexborisov** [comment]
Hi @iacore 

I can assume you are using the backend (HTMLParser) from Modest, which I highly discourage.
Lexbor has nothing wrong with the selectors, and your example works fine.

Try using the [backend from Lexbor](https://github.com/rushter/selectolax?tab=readme-ov-file#available-backends). 

The python module is being developed by @rushter (thank him so much for that).
I think he is aware of this problem in the Modest backend.

**Comment by iacore** [comment]
Hi @lexborisov, thanks for making such a wonderful library!

I had another problem with lexbor unable to parse a very malformed file that's neither XML or HTML. Is this in the scope of lexbor?

**Comment by lexborisov** [comment]
@iacore 

Lekbor can even parse a binary.
Depends on what you mean. XML and XHTML are different. Lexbor is a library for working with HTML (modern and old).
