### ISSUE TITLE
Help using vcpkg windows g++

### ISSUE THREAD

**Issue by matt1309** [lexbor/lexbor#216]
Hi, 

I'm potentially doing something daft as very much a beginner (sorry in advance) but getting linker errors:

` undefined reference to "__imp_lxb_html_document_create"
 undefined reference to "__imp_lxb_html_document_parse"
undefined reference to "__imp_lxb_css_parser_create"
undefined reference to "__imp_lxb_css_parser_init"
`

(and many more but just as an example). 

I've installed lexbor via vcpkg using the below:

`vcpkg install lexbor:x64-mingw-static`

I'm using vs code so my tasks.json is like this:
What am i missing, is there a dependency im not including and should be?

"tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe build active file",
            "command": "C:\\msys64\\ucrt64\\bin\\g++.exe",
            "args": [
                "-I./",
                "-I c:/Users/test/Desktop/VS Code Project files/installed/x64-mingw-static/include/",
                "-fdiagnostics-color=always",
                "-g",
                "ConfigClass.cpp",
                "${file}", // Compile main.cpp
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe",
                "-Lc:/Users/test/Desktop/VS Code Project files/vcpkg/installed/x64-mingw-static/lib",
                "-L./lib",
                "-lcurl", 
                "-lws2_32",
                "-lwldap32",
                "-lwsock32",
                "-lcrypt32",
                "-ladvapi32",
                "-lwsock32",
                "-lcrypt32",
                "-ladvapi32",
                "-lbcrypt",
                "-lz",
                "-lpugixml",
                "-llexbor_static",
                "-Wno-pedantic-ms-format"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": "build",
            "detail": "Task generated by Debugger."
       
       
        }
    ],
    "version": "2.0.0"
}

**Comment by vtorri** [comment]
try to embde static lib of lexbor between `-Wl,-Bstatic` and -Wl,-Bdynamic`` in that order:

```
"-Wl,-Bstatic",
"-llexbor_static",
"-Wl,-Bdynamic"
```

ld will choose the static lib of lexbor.

you may also need to pass `-DLEXBOR_STATIC` to the preprocessor

**Comment by vtorri** [comment]
the problem is the flags passed to the linker : `-L/path/to/lib -llexbor_static` is for dynamic linking. Hence the error messages `undefined reference to "__imp_******` which means exactly that the link is supposed to be done against the DLL, and not the static lib. The linker expects the symbols to be in a DLL, which is not the case.

That's why I proposed the -B options of the linker. Another solution is to pass to the linker `/path/to/liblexbor_static.a` (or whatever the name of the static lib is) instead of `-llexbor_static`

**Comment by matt1309** [comment]
Thanks @vtorri 

That's solved it!! (Both the -Bstatic and the -D were needed)
