### ISSUE TITLE
How to quickly determine whether a node is hidden？

### ISSUE THREAD

**Issue by myamoroso** [lexbor/lexbor#219]
The node has id and some class properties,  How to quickly determine whether it is hidden？ Thanks a lot!

html:
< div id="info" class="fl" />
< div id="d_hidden" class="m_hidden block" />
< div  class="m_hidden" />
< div id="d_hidden" class="block" />

in a css file:
#info{
    color: #777777;
}

#d_hidden {
    display: none;
}

.fl {
    color: #777777;
}

.m_hidden {
    display: none;
}

.block {
    color: #777777;
}

**Comment by lexborisov** [comment]
Hi, @myamoroso 

Layout is in development. It is now available to assign CSS styles to HTML elements by Selectors.
But calculations of block sizes, inlines and glyphs in general are in development.

There was a plan to roll out the first version of layout at the end of March. But life has made its changes.
