### ISSUE TITLE
query or xpath support ?

### ISSUE THREAD

**Issue by patrickkh7788** [lexbor/lexbor#23]
Is this lib support XPATH query ?  

to select like: "#id div > a[href]".

should I use modest_finder_by_selectors_list ?

**Comment by patrickkh7788** [comment]
I end up use modest, work great. only problem is I can not get innerText with myhtml_node_text

**Comment by Azq2** [comment]
**html5_dom_recursive_node_inner_text** implements innerText by spec: https://github.com/Azq2/perl-html5-dom/blob/bec663cf9c786685b0f98ffd46d5429206727491/utils.c#L439

How to use: https://github.com/Azq2/perl-html5-dom/blob/master/DOM.xs#L1774

**Comment by Azq2** [comment]
Or if you want more simple **textContent**: https://github.com/Azq2/perl-html5-dom/blob/master/DOM.xs#L64

**Comment by Azq2** [comment]
In my HTML5::DOM you can find 9999 in 1 complete examples of usage myhtml. :)

**Comment by ilyazub** [comment]
@lexborisov What do you think about porting [`modest_finder_by_selectors_list`](https://github.com/lexborisov/Modest/blob/393338d994c921705ff71dfbd1d98ceb31328f14/source/modest/finder/finder.c#L151-L173) to lexbor? I'd like to help, but your guidance is needed.

**Comment by lexborisov** [comment]
@ilyazub 

I already have selectors for the lexbor project ready.
I will publish soon.

Thanks!
