### ISSUE TITLE
Test failure: 105 - lexbor_punycode_base

### ISSUE THREAD

**Issue by thierry-FreeBSD** [lexbor/lexbor#230]
I ported lexbor to FreeBSD, and everything seems OK, excepted a failure in the test 105 - lexbor_punycode_base:
```
Test project /usr/ports/www/lexbor/work/.build
    Start 105: lexbor_punycode_base
1/1 Test #105: lexbor_punycode_base .............***Failed    0.01 sec
Run 'lexbor/punycode/base' tests:
1) encode_chr: ok
2) encode_big_buffer: ok
3) encode_big_buffer_edge: ok
4) decode_chr: ok
5) decode_big_buffer: Failure
/usr/ports/www/lexbor/work/lexbor-2.3.0/test/lexbor/punycode/base.c:150:decode_big_buffer
6) decode_big_buffer_edge: ok
7) cp: ok
Failed: 1
Total: 7
```
Does it work on the other systems?

**Comment by lexborisov** [comment]
Hi @thierry-FreeBSD 

Exactly what system are you using? Compiler?

Works and tests great on many OS's:
```
CentOS, Debian, Fedora, RHEL, Ubuntu, macOS, Windows
```

Can you build the project with ASAN?

```
cmake path/to/lexbor -DLEXBOR_BUILD_TESTS=ON -DLEXBOR_BUILD_WITH_ASAN=ON
make -j
```

and run test and send out info

```
./test/lexbor/punycode/base 
```

**Comment by thierry-FreeBSD** [comment]
Thanks for your quick answer!
lexbor is the released v2.3.0, on FreeBSD 15.0-CURRENT, with clang 18.1.4.
And yes, if built with ASAN all the test pass:
`100% tests passed, 0 tests failed out of 151`
Without ASAN, here is the output of the failed test:
```
$ ./test/lexbor/punycode/base
Run 'lexbor/punycode/base' tests:
1) encode_chr: ok
2) encode_big_buffer: ok
3) encode_big_buffer_edge: ok
4) decode_chr: ok
5) decode_big_buffer: Failure
/usr/ports/www/lexbor/work/lexbor-2.3.0/test/lexbor/punycode/base.c:150:decode_big_buffer
6) decode_big_buffer_edge: ok
7) cp: ok
Failed: 1
Total: 7
```

**Comment by lexborisov** [comment]
@thierry-FreeBSD 

Thanks for the report!
I figured out the problem. There will be a patch tomorrow night.

**Comment by lexborisov** [comment]
@thierry-FreeBSD 

Sorry for the delay. Fixed in [https://github.com/lexbor/lexbor/commit/cf28627eb197b0f66190583047695bba4b2d3009](https://github.com/lexbor/lexbor/commit/cf28627eb197b0f66190583047695bba4b2d3009).

**Comment by thierry-FreeBSD** [comment]
Great, it works!
