### ISSUE TITLE
Incorrect memset

### ISSUE THREAD

**Issue by nielsdos** [lexbor/lexbor#235]
The following code seems incorrect to me, but I'm not sure what it's supposed to be instead:

https://github.com/lexbor/lexbor/tree/05106330d67933746b4e9a27eb86011b7c36a92a/source/lexbor/css/log.c#L45

mraw is defined here as a pointer:

https://github.com/lexbor/lexbor/blob/05106330d67933746b4e9a27eb86011b7c36a92a/source/lexbor/css/log.h#L34-L39

So taking the address and using memset with size of lexbor_mraw_t causes an overflow.

**Comment by lexborisov** [comment]
@nielsdos 

Even I didn't immediately understand this code snippet.

We should delete this line `memset(&log->mraw, 0, sizeof(lexbor_mraw_t));` it makes no sense.
