### ISSUE TITLE
Potentially inverted NULL check?

### ISSUE THREAD

**Issue by nielsdos** [lexbor/lexbor#236]
From a static analyser I found the following report.

Here `pos` is dereferenced:

https://github.com/lexbor/lexbor/blob/05106330d67933746b4e9a27eb86011b7c36a92a/source/lexbor/html/tree.c#L406-L407

But later on, `pos` is NULL checked:

https://github.com/lexbor/lexbor/blob/05106330d67933746b4e9a27eb86011b7c36a92a/source/lexbor/html/tree.c#L414-L416

I don't know enough about these algorithms to know whether this is a true or false positive.

**Comment by lexborisov** [comment]
@nielsdos 

The static analyzer has almost correctly highlighted a strangeness in the code.

The `lxb_html_tree_create_element_for_token` function actually takes the last argument, but it is not used in any way in the function.
Here you should change the input arguments for the `lxb_html_tree_create_element_for_token` function and then the code will become cleaner and clearer.

I'll make a patch for it.

**Comment by lexborisov** [comment]
@nielsdos 

Thanks for the report! Fixed in [aaa722f](https://github.com/lexbor/lexbor/commit/aaa722f9a44a486f361e4266ff322afcf7d6421a).

**Comment by nielsdos** [comment]
Thanks a lot!
