### ISSUE TITLE
How to know same TAG ?

### ISSUE THREAD

**Issue by octalflow** [lexbor/lexbor#253]
HTML:
		\<p\>
		  In chemistry, \<b\>alcohol\</b\> is an organic compound that 
		  carries at least one \<i\>hydroxyl functional group\</i\> 
		  (−OH) bound to a saturated carbon atom. 
		  The term alcohol originally referred to the primary 
		  alcohol ethanol (\<i\>ethyl alcohol\</i\>), which is used as 
		  a drug and is the main alcohol present in alcoholic beverages. 
		\</p\>

call lxb_dom_node_simple_walk()

How to know same P tag message ?

**Comment by lexborisov** [comment]
Hi @octalflow 

Sorry, but I don't understand your question.
