### ISSUE TITLE
function name misspelling（eof->oef）

### ISSUE THREAD

**Issue by coolight7** [lexbor/lexbor#254]
Hi,
- I seem to have found a spelling problem in a function defined in the `state.h` file (line 106), `lxc_html_tokenxited_end_oef`, where the end of `oef` should be `eof`.
![image](https://github.com/user-attachments/assets/5217e177-0e0f-4e4b-be41-44935a79235e)

**Comment by lexborisov** [comment]
@coolight7 

Thanks for the report!
