### ISSUE TITLE
[Question] Force failure when input is javascript only?

### ISSUE THREAD

**Issue by TechnikEmpire** [lexbor/lexbor#255]
Hi there,

I'm using Lexbor within a proxy and I'm finding, as usual with HTTP, there are some jerks running servers that return "text/html" content type for pure javasacript payloads. This makes my proxy want to feed it to Lexbor , and I would expect that Lexbor would simply fail (since there is no HTML present whatsoever). Instead it appears to be succeeding, as the status returned is `OK`. My code, not being told of any failure, then re-serializes the result as `<html><body></body></html>......THE_JAVASCRIPT.......`.

Any advice?

Thanks for your time and library.

**Comment by lexborisov** [comment]
Hi @TechnikEmpire 

HTML parser will parse (and restore as HTML) any data, even binary data. That's how HTML works.
Basically, your question is how to understand what the server returned. Especially when the server returns an wrong HTTP header.

I don't have an off-the-shelf algorithms on how to accurately determine HTML, JavaScript, CSS or whatever else a server might return under a text/html header.
