### ISSUE TITLE
Copy elements/nodes

### ISSUE THREAD

**Issue by trikko** [lexbor/lexbor#31]
Is there a way to make a (deep?) copy of an element/node? I can't find any fast way to do this.
Copying element content and reparsing seems not the best performance option...

**Comment by lexborisov** [comment]
Hi @trikko ,
There are currently no cloning features. This is not complicated functionality and I think it is necessary to add it. I'll do it soon.

Thank you for the report!

**Comment by lexborisov** [comment]
@trikko 

Added in https://github.com/lexbor/lexbor/commit/0c4010b10a922a45513d67beec0ddd29c2951f85.
