### ISSUE TITLE
Feature request: Option to skip whitespace nodes

### ISSUE THREAD

**Issue by kostya** [lexbor/lexbor#36]
I compare time and memory usage with myhtml parse 10 times this page: https://www.dropbox.com/s/cq3zonfmsvrcg4k/5.html.gz?dl=0

* myhtml: 10.52s, 200.9Mb
* lexbor: 8.75s, 179.9Mb
* myhtml(TREE_PARSE_FLAGS_SKIP_WHITESPACE_TOKEN): 6.47s, 140.0Mb

so if lexbor can use also this option it would be nice.

**Comment by lexborisov** [comment]
@kostya 

I’ll think about how to do it right.

I will update the lexbor soon (internal work with tag attributes will change) and it will become even faster.

**Comment by vtorri** [comment]
what about adding a benchmark test in source ?

**Comment by lexborisov** [comment]
I will add them later.

**Comment by kostya** [comment]
btw, why whitespace nodes needed?, i see no reason, only for serialize purposes.

**Comment by lexborisov** [comment]
@kostya 

For example (try in browser):
```HTML
text<span> </span>space
```
or
```HTML
text<div style="display: inline;"> </div>space
```
or
```HTML
text<span>
</span>space
```

**Comment by kostya** [comment]
If i understand correct, all kind of white space strings, can be replaced with single space (which can be as another type of node, without text storage).

**Comment by lexborisov** [comment]
This will break many tests. But even that doesn’t matter. The bottom line is that this will not give an increase in speed. The problem is make the token and going through the "circle of hell" in building a tree.

**Comment by lexborisov** [comment]
Each user can implement this themselves by modifying the tokenizer callback.

Something like, 

```C
lxb_html_tokenizer_callback_token_done_set(tkz, blah_blah_callback, tree);

static lxb_html_token_t *
blah_blah_callback(lxb_html_tokenizer_t *tkz,
                   lxb_html_token_t *token, void *ctx)
{
    lxb_status_t status;

    if (token->tag_id == LXB_TAG__TEXT) {
        /* Here we check whether the string is empty or not. */
        if (ws == true) {
            return token;
        }
    }

    status = lxb_html_tree_insertion_mode(ctx, token);
    if (status != LXB_STATUS_OK) {
        tkz->status = status;
        return NULL;
    }

    return token;
}
```
