### ISSUE TITLE
undefined symbols when building tests

### ISSUE THREAD

**Issue by vtorri** [lexbor/lexbor#41]
problem: some symbols (like lxb_encoding_single_index_windows_874 or lxb_encoding_res_map) are declared as extern. On UNIX, there is no problem because by default everything is exported by the linker. On Windows, it's the contrary, every symbol is hidden.

so they must be declared with LXB_API. Note that it will also fix undef ref on unix if -fvisibility=hidden is passed to the compiler.

**Comment by lexborisov** [comment]
@vtorri 

Thanks for the report!  I’ll fix it soon.
