### ISSUE TITLE
Submit to vcpkg?

### ISSUE THREAD

**Issue by CrazyKidJack** [lexbor/lexbor#50]
@lexborisov 
Hello, I was wondering if this library could be submitted to be added to [vcpkg](https://github.com/microsoft/vcpkg). I'm fairly certain I can't just "do it myself"... but it would be really convenient to have it available in a package manager like that.

Here's a direct link to the [vcpkg info page on submitting new packages](https://github.com/microsoft/vcpkg/blob/master/CONTRIBUTING.md)

**Comment by lexborisov** [comment]
@CrazyKidJack 

It seems to me that anyone can do this. The problem is wider. In addition, to simply add a package, it must be supported.

**Comment by CrazyKidJack** [comment]
#1 Ok if anyone can do it, then I suppose I will :)

#2 What is the problem you are referring to? What do you mean by "it must be supported"?

**Comment by lexborisov** [comment]
@CrazyKidJack 

> Ok if anyone can do it, then I suppose I will :)

Great!

> What is the problem you are referring to? What do you mean by "it must be supported"?

Should be supported: track changes (releases) in the lexbor, adding new versions to the package manager (vcpkg).

**Comment by CrazyKidJack** [comment]
Ah yes, of course if and when I notice a new package come out I would update it.

**Comment by lexborisov** [comment]
@CrazyKidJack 

> That being said, I want to be clear that I have permission to submit the following to vcpkg:
> ![image](https://user-images.githubusercontent.com/43480837/73606911-3c194280-4575-11ea-8360-c3de5d0fa262.png)

This is a standard thing. This agreement is not for the lexbor code, but for a pull request. It is ok.

**Comment by vtorri** [comment]
there is also my package installer : https://github.com/vtorri/ewpi

**Comment by CrazyKidJack** [comment]
@vtorri I have not heard of that package manager??

Also, I am not *super* experienced with lexbor yet, do you mind if I ask what kinds of imporvements you think it needs so that I may better understand its shortcomings. (I'm curious becuase perhaps I shouldn't add it to the vcpkg package manager either.. especially considering that one is a more widely used one and verified by Microsoft

**Comment by vtorri** [comment]
@CrazyKidJack it's normal, i've written it last year, for more or less my own purposes, but it can be used for any project which needs dependencies (i've written it for the Enlightenment project).

and it's more a package installer (compile and install from sources with the same toolchain, and reproductable), than a package manager (no uninstall for example), but dependencies are taken into account

**Comment by CrazyKidJack** [comment]
@vtorri I see and thank you for telling me about that new package installer, I will check it out!

However, what improvements were you looking for in lexbor?

**Comment by vtorri** [comment]
at least font parsing, because that's all the purpose of an html rendering lib imho, but alex maybe have another opinion

**Comment by alexkreidler** [comment]
Any updates on this?

It was closed but I don't see lexbor when I search vcpkg:
```
vcpkg search lexbor

If your library is not listed, please open an issue at and/or consider making a pull request:
    https://github.com/Microsoft/vcpkg/issues
```

**Comment by Kamrulhasan12345** [comment]
@lexborisov, Can this package be available in vcpkg?

**Comment by paulocoghi** [comment]
@Kamrulhasan12345 as per the previous comments, you can publish this package on vcpkg yourself, as long as you take responsibility to update the publication whenever a new version is released here on Github.

**Comment by AlexandreAero** [comment]
any news about this? It's 2023, vcpkg is becoming a standard..
