### ISSUE TITLE
Compiler error on package use

### ISSUE THREAD

**Issue by CrazyKidJack** [lexbor/lexbor#52]
@lexborisov 
I have successfully gotten the library to compile on my machine (x64-windows).

But when I `#include<lexbor/html/html.h>` I get compiler errors complaining about the use of the macro `interface`. These errors come from the "document.h" and "interface.h" files.

The macro itself is defined in the "combaseapi.h" file.

Here is a screen shot of the errors... on the left you see my code with the include statement, on the right you see one of the uses of the `interface` macro that is causing a compiler error:
![image](https://user-images.githubusercontent.com/43480837/73821025-9eae5080-47b8-11ea-9f0b-639a84ecf0e6.png)

**Comment by CrazyKidJack** [comment]
Here is another screen shot showing the list of all of the uses of the macro that I believe to be causing errors. On the right you can see the definition of the `interface` macro is simply "struct" and in all of the uses in the list on the left, the macro is used without any other identifier/typename which is why I think it is causing errors: 
![image](https://user-images.githubusercontent.com/43480837/73821241-17151180-47b9-11ea-9af8-5d3eeafa5710.png)

**Comment by CrazyKidJack** [comment]
perhaps I'm including the wrong file? I just assumed that to use the html module, one should include the html.h file... but there are lots of headers in there and I don't see clear documentation on the website of which header is for what purpose?

**Comment by lexborisov** [comment]
@CrazyKidJack 
About interface, I replace it today.

About includes, please, see [examples](https://github.com/lexbor/lexbor/tree/master/examples/lexbor/html), like a [this](https://github.com/lexbor/lexbor/blob/master/examples/lexbor/html/document_parse.c)

**Comment by CrazyKidJack** [comment]
@lexborisov 
I looked at the examples to figure out includes... but...
#1 Many (if not all) of the examples include a custom "base.h" file that I do not see actually provided in any of the modules.

#2 That file doesn't have declarations/definitions for *everything* even if it *was* provided... so it is still difficult to know which *other* files need to be included

**Comment by lexborisov** [comment]
@CrazyKidJack 

1. File include as "base.h" (current directory), file in [html exampes directory](https://github.com/lexbor/lexbor/blob/master/examples/lexbor/html/base.h).
2. Apparently, for each module (hmtl, css), I need to create a header file that will include all the necessary headers.

Thanks for the report! I will make improvements.

**Comment by lexborisov** [comment]
@CrazyKidJack 

Thanks for the report! Fixed.
Please, try current version.
