### ISSUE TITLE
Abnormally high memory usage in exceptional cases

### ISSUE THREAD

**Issue by foobar27** [lexbor/lexbor#53]
When I decompress the attached file [broken.html.gz](https://github.com/lexbor/lexbor/files/4194762/broken.html.gz) and execute

> ./html2sexpr broken.html

the example program uses more than 12GB RAM and gets killed by the kernel. The uncompressed version of the file is 5MB.

The file seems to be degenerated in a systematic way, so I I tried to break down the file with the following commands:

> export $N=100
> head -n $N broken.html > new.html
> tail -n $N broken.html >> new.html
> /usr/bin/time -f '%M' ./html2sexpr new.html

and I plotted the result into a graph:

https://docs.google.com/spreadsheets/d/1CXq7bcITtlaiS1hh-MILxQUUzvf8yuxEG9CZagEZ5K0/edit?usp=sharing

It looks as if the memory growth is quadratic, so it can grow very quickly.

I can reproduce the problem with the latest master version, and with the release v0.4.0.

Is there a way to optimize the parsing algorithm here? Firefox and chrome manage to open the file pretty easily.

**Comment by lexborisov** [comment]
@foobar27 

An interesting test for the memory locator. This is easy to fix, in the near future I will prepare a patch.
In this case, the problem is a lot of new lines. Problem for my memory locator.

Thanks for the report!

**Comment by lexborisov** [comment]
@foobar27 

Fixed.
Thanks again for the report!

**Comment by foobar27** [comment]
Thanks for the fast fix! I confirm it's working.
