### ISSUE TITLE
How use this library as git sub-module?

### ISSUE THREAD

**Issue by LinArcX** [lexbor/lexbor#59]
Hi. I'm curious to know how use this library as git-submodule. Actually I'm going to create an application that is going to use this library and i will probably create a package for my application for void-linux, arch, ...

So i don't want to use distributions packages. I want to embed this library as git submodule. So if usere want to build my project, they'll automatically first fetch and build lexbor and then build my project.

And i [only want to use ](https://github.com/lexbor/lexbor#separately)liblexbor-html library that depends on liblexbor-core, liblexbor-dom, liblexbor-tag, liblexbor-ns according to readme.

**Comment by vtorri** [comment]
maybe this will help : 
https://github.blog/2016-02-01-working-with-submodules/

**Comment by LinArcX** [comment]
Ok. This is my project:
https://github.com/LinArcX/mgr

As you can see i've added lexbor as sub-module and also [add it in the root of my project CMakeLists.txt as subdirectory.](https://github.com/LinArcX/mgr/blob/master/CMakeLists.txt#L7)

I tried to compile it via:
`cd build; cmake -Wdeprecated  -Wno-dev -DCMAKE_BUILD_TYPE=Debug ../;`

It correctly compile lexbor submodule but when it comes to compile core, it gives me this error:
```
/mnt/D/workspace/c++/cpp/projects/active/mgr/core/main.cpp:1:10: fatal error: 'lexbor/core/fs.h' file not found                                      
  #include "lexbor/core/fs.h"                                                                                                                          
           ^~~~~~~~~~~~~~~~~~                                                                                                                          
  1 error generated.                                                                                                                                   
  make[2]: *** [core/CMakeFiles/mgr.dir/build.make:66: core/CMakeFiles/mgr.dir/main.cpp.o] Error 1                                                     
  make[2]: Leaving directory '/mnt/D/workspace/c++/cpp/projects/active/mgr/build'                                                                      
  make[1]: *** [CMakeFiles/Makefile2:195: core/CMakeFiles/mgr.dir/all] Error 2                                                                         
  make[1]: Leaving directory '/mnt/D/workspace/c++/cpp/projects/active/mgr/build'                                                                      
  make: *** [Makefile:155: all] Error 2 
```

**Comment by vtorri** [comment]
the fs.h file is actually correctly installed here : 
/opt/lexbor_shared/include/lexbor/core/fs.h

but as you don't install it, it is there in the source tree of lexbor : 

$ find . -name fs.h
./source/lexbor/core/fs.h

so maybe you should add -I../lexbor/source for CFLAGS of your src/CMakeList.txt

**Comment by LinArcX** [comment]
Something like this:
https://github.com/LinArcX/mgr/blob/master/core/CMakeLists.txt#L1
But still don't work.

**Comment by lexborisov** [comment]
@LinArcX 

Hi, thanks for using lexbor.

You can use `include_directories` in `core/CMakeList.txt`.
```
add_executable(mgr main.cpp)
target_link_libraries(mgr PRIVATE mgrabber lexbor)

include_directories("../lexbor/source")
```

But in general, the current approach seems strange. I think you need to better think about the structure of the project.

**Comment by LinArcX** [comment]
@lexborisov Thanks. It's working like a charm :)

Actually i have two reasons:
1. Learning purpose.
2. Provide my application(mgr) for distros that don't have lexbor as a package in their repositories.(like void, nixos,..)
