### ISSUE TITLE
CmakeList.txt : wrong test to compile  separated libs ?

### ISSUE THREAD

**Issue by vtorri** [lexbor/lexbor#60]
in top level CmakeList.txt arounf line 171 : 

```
IF(NOT LEXBOR_BUILD_SEPARATELY)
    FOREACH(module ${LEXBOR_MODULES})
```
etc...

that is, within that IF test, separated libs are managed. So why the **NOT** in IF ?

**Comment by lexborisov** [comment]
@vtorri 

Everything is right here. If `LEXBOR_BUILD_SEPARATELY` is not defined, then we must load all the modules for one liblexbor (single).
