### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by twg-group** [lexbor/lexbor#64]
Can you help me, how to use this lib?  I try to write custom wrapper class.. but can't...

```
#include "lexbor/html/html.h"
#include "lexbor/dom/dom.h"
```

```
Scanning dependencies of target test
[ 50%] Building CXX object CMakeFiles/test.dir/test.cpp.o
[100%] Linking CXX executable test
CMakeFiles/test.dir/test.cpp.o: In function `lxb_dom_collection_make':
/usr/local/include/lexbor/dom/collection.h:46: undefined reference to `lxb_dom_collection_create'
/usr/local/include/lexbor/dom/collection.h:47: undefined reference to `lxb_dom_collection_init'
/usr/local/include/lexbor/dom/collection.h:50: undefined reference to `lxb_dom_collection_destroy'
CMakeFiles/test.dir/test.cpp.o: In function `ParserLexbor::initParser()':
/home/mat/dev/zserver/include/ParserLexbor.hpp:24: undefined reference to `lxb_html_parser_destroy'
/home/mat/dev/zserver/include/ParserLexbor.hpp:26: undefined reference to `lxb_html_parser_create'
/home/mat/dev/zserver/include/ParserLexbor.hpp:27: undefined reference to `lxb_html_parser_init'
CMakeFiles/test.dir/test.cpp.o: In function `ParserLexbor::setHtml(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/mat/dev/zserver/include/ParserLexbor.hpp:34: undefined reference to `lxb_html_parse'
CMakeFiles/test.dir/test.cpp.o: In function `ParserLexbor::getByCss(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/mat/dev/zserver/include/ParserLexbor.hpp:50: undefined reference to `lxb_dom_elements_by_class_name'
collect2: error: ld returned 1 exit status
CMakeFiles/test.dir/build.make:83: recipe for target 'test' failed
make[3]: *** [test] Error 1
CMakeFiles/Makefile2:79: recipe for target 'CMakeFiles/test.dir/all' failed
make[2]: *** [CMakeFiles/test.dir/all] Error 2
CMakeFiles/Makefile2:86: recipe for target 'CMakeFiles/test.dir/rule' failed
make[1]: *** [CMakeFiles/test.dir/rule] Error 2
Makefile:118: recipe for target 'test' failed
make: *** [test] Error 2
```

**Comment by vtorri** [comment]
it depends : have you compiled lexbor with separated lib or not ?

when you have "undefined reference" message, you have forgotten to pass -lthe_lib to the linker

In your case, if you have compiled without separated lib (the default build of lexbor), you have to pass

-llexbor

to the linker. Additionally, you also have to pass -L/path/to/lib, where /path/to/lib is the directory where liblexbor.so is located

**Comment by twg-group** [comment]
Can you share CMakeLists.txt please

**Comment by vtorri** [comment]
if lexbor is installed in /usr/local try to add to your cmake command : 

-DCMAKE_EXE_LINKER_FLAGS="-L/usr/local/lib -llexbor"

**Comment by lexborisov** [comment]
@twg-group 

Please, show you CMakeLists.txt and sources (If they are not secret). and what commands are you make project.

**Comment by twg-group** [comment]
I use the CLion IDE, you may need to change some configs ... but, this is the first time I get a build / compile error for free libraries ...

Library successfully builded without any flags.

CMakeLists.txt
`cmake_minimum_required(VERSION 3.15)
project(zserver)

set(CMAKE_CXX_STANDARD 14)
set(PLATFORM_SPECIFIC_LIBS "-lpthread")

add_executable(test test.cpp)

find_package(cppzmq REQUIRED)

target_link_libraries(test cppzmq curl -lpthread gtest -llexbor)`

**Comment by twg-group** [comment]
Привет! Я не знаю, что случилось, но ошибка пропала, сейчас всё ОК! Чудеса.. я ничего не менял, просто ребилдил из IDE.

--
Возможно потому, что мне пришлось пересобрать библиотеку из-за бага [#63 ](https://github.com/lexbor/lexbor/issues/63)

**Comment by twg-group** [comment]
Not yet... no errors when i link with `cppzmq` lib wtf... without i got:

`find_package("-llexbor" REQUIRED)`

```
CMake Error at CMakeLists.txt:18 (find_package):
  By not providing "Find-llexbor.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "-llexbor",
  but CMake did not find one.

  Could not find a package configuration file provided by "-llexbor" with any
  of the following names:

    -llexborConfig.cmake
    -llexbor-config.cmake

  Add the installation prefix of "-llexbor" to CMAKE_PREFIX_PATH or set
  "-llexbor_DIR" to a directory containing one of the above files.  If
  "-llexbor" provides a separate development package or SDK, be sure it has
  been installed.
```

or without `find_package`:

`/home/mat/dev/zserver/cmake-build-debug/test: error while loading shared libraries: liblexbor.so.1: cannot open shared object file: No such file or directory`

**Comment by twg-group** [comment]
Its all ok! Need to drink less beer ...
