### ISSUE TITLE
Swift package

### ISSUE THREAD

**Issue by robb** [lexbor/lexbor#65]
Do you think it would be possible to offer a `Package.swift` file for easy integration with the Swift package manager?

I see [you're using Xcode](https://github.com/lexbor/lexbor/tree/20017bdc1ecc9c950c9edf0a3a070d6ffd1f4618/dev/xcode) for development so I figured it might be something you'd consider for the main repo.

**Comment by lexborisov** [comment]
Hi @robb 

You can if you will support this in the future.
