### ISSUE TITLE
lxb_dom_node_text_content and <br> elements

### ISSUE THREAD

**Issue by evanmiller** [lexbor/lexbor#72]
Thank you for the library! I am trying to extract human-readable text from an element and its descendants similar to `.textContent`. However I am finding that

```
<div>John Lennon<br>Paul McCartney</div>
```

is returned as `John LennonPaul McCartney` when using `lxb_dom_node_text_content`.

I would like `<br>` elements replaced with newlines, and non-semantic whitespace replaced with single spaces. How would you suggest I proceed?

**Comment by lexborisov** [comment]
Hi @evanmiller 

Perhaps there is an error in the processing of elements. I am studying the specification for [textContent](https://dom.spec.whatwg.org/#dom-node-textcontent). Over the next day I will try to correct the behavior, or explain in detail what is happening.

Thanks for the report!

**Comment by lexborisov** [comment]
@evanmiller 

I studied the specification again, looked at how it was done in modern browsers, and I can say that the current behavior is correct.

Currently, the behavior you described is not in the library. 
You can do something similar yourself, here is an example:

```C
#include "lexbor/html/html.h"
#include "lexbor/dom/dom.h"


static lexbor_action_t
simple_walker(lxb_dom_node_t *node, void *ctx)
{
    lexbor_str_t *str;

    switch (lxb_dom_node_tag_id(node)) {
        case LXB_TAG__TEXT:
            str = &lxb_dom_interface_text(node)->char_data.data;

            printf("%.*s", (int) str->length, (char *) str->data);
            break;

        case LXB_TAG_BR:
            printf("\n");
            break;

        case LXB_TAG__EM_COMMENT:
            /* Skip comment and his children's. */
            return LEXBOR_ACTION_NEXT;

        default:
            break;
    }

    return LEXBOR_ACTION_OK;
}

int main(void)
{
    lxb_status_t status;
    lxb_html_document_t *document;

    lxb_char_t data[] = "<div>John Lennon<br>Paul McCartney</div>";
    size_t length = sizeof(data) - 1;

    document = lxb_html_document_create();
    if (document == NULL) {
        printf("Failed to create document\n");
        return 1;
    }

    status = lxb_html_document_parse(document, data, length);
    if (status != LXB_STATUS_OK) {
        printf("Failed to parse HTML\n");
        return 1;
    }

    lxb_dom_node_simple_walk(lxb_dom_interface_node(document), simple_walker,
                             NULL);

    lxb_html_document_destroy(document);

    return 0;
}
```

**Comment by evanmiller** [comment]
Okay, that works for me. Thanks for the solution.
