### ISSUE TITLE
Skipping nodes in lxb_dom_node_simple_walk?

### ISSUE THREAD

**Issue by evanmiller** [lexbor/lexbor#73]
In #72 I was given a solution for walking over the DOM tree. The example includes

```
        case LXB_TAG__EM_COMMENT:
        case LXB_TAG_SCRIPT:
        case LXB_TAG_STYLE:
            /* Skip node and his children's. */
            return LEXBOR_ACTION_NEXT;
```

However, I find that `LEXBOR_ACTION_NEXT` does not actually skip the nodes. Indeed there is no special handling of this return value in:

https://github.com/lexbor/lexbor/blob/master/source/lexbor/dom/interfaces/node.c#L248

And it appears that the other clients of `lxb_dom_node_simple_walk` assume that `LEXBOR_ACTION_NEXT ` does not skip.

I would like a solution for skipping nodes during a node walk without writing my own walking function.

**Comment by lexborisov** [comment]
@evanmiller 

Fixed! Thanks for the report.
