### ISSUE TITLE
Some compilers do not have "stdbool. h ", which is included in "lexbor\core\types.h"

### ISSUE THREAD

**Issue by IYinxf** [lexbor/lexbor#74]
Compilation using VS2010 failed, missing header file.
For the moment, I'll replace "#include <stdbool. h >" with the following code:
`
typedef int lxb_bool;

#define bool lxb_bool
#define false 0 
#define true  1
`

**Comment by vtorri** [comment]
lexbor is written in C99, so you need to have a C compiler which support a minimum of the C99 features

is there any reason to not update VS to at least VS 2015 ? I think that VS 2015 can support C99 bool

**Comment by IYinxf** [comment]
> lexbor is written in C99, so you need to have a C compiler which support a minimum of the C99 features
> 
> is there any reason to not update VS to at least VS 2015 ? I think that VS 2015 can support C99 bool

You're right. I shouldn't give up trying to keep up with The Times just because I'm too lazy to change my IDE.
In addition, I found that there are few comments in the code to explain the function's functionality. Will you improve the documentation later?

**Comment by vtorri** [comment]
i suppose that @lexborisov will answer this question

**Comment by lexborisov** [comment]
@IYinxf 

The minimum version of C for the project is C99.
The documentation will be update, at the moment there is simply not enough time.

**Comment by IYinxf** [comment]
> @IYinxf
> 
> The minimum version of C for the project is C99.
> The documentation will be update, at the moment there is simply not enough time.

Ok, I will learn and use it. thanks
