### ISSUE TITLE
Wrong tag-detection when inside <script>-state

### ISSUE THREAD

**Issue by PhiTux** [lexbor/lexbor#78]
Hi, 
looks like I found a bug. I do use (only!) the tokenizer to parse html-code and to detect tags. This works fine except of the following behavior.

You can repeat it with the "official" tokenizer/simple - example.
When changing the html-code to contain some script-code containing a "<"-sign (which is quite common in JS as a comparator), then the tokenizer sometimes thinks a new tag would be opened and handles all following code as attribute=value. Beside other errors this yields to a broken close-tag.

A minimal working example for the html-code (line 83 in the example):
`<script>var a = b<c?d:e</script>`

This yield to the result:
`<script>var a = b<c?d:e< script>`

The original code where I recognized this behavior was when parsing the youtube.com page. The explicit script-code embedded in the page was in this case:
[script.txt](https://github.com/lexbor/lexbor/files/4573547/script.txt)

**Comment by lexborisov** [comment]
Hi @PhiTux 

All work is fine.

The tokenizer knows nothing about tags (except comments). There are "special" tags such as `<script>`, `<style>`, `<textarea>`, `<title>` and so on.

But, in the tokenizer there are all stages for the correct parsing of such tags. It’s just that someone should switch it to the necessary stages. The parser (tree/dom builder) is currently doing this.

Please, [read my article about it](https://lexbor.com/articles/html/#tokenizer).

You can try to do this:
```C
static lxb_html_token_t *
token_callback(lxb_html_tokenizer_t *tkz, lxb_html_token_t *token, void *ctx)
{
    if (token->tag_id != LXB_TAG_SCRIPT) {
        lxb_html_tokenizer_state_set(tkz,
                                   lxb_html_tokenizer_state_script_data_before);
    }

    return token;
}
```

**Comment by PhiTux** [comment]
Hello @lexborisov 

thanks for that fast answer! Now it took me some time to go into it...
Makes sense to switch the states. 

So do I understand it right, that I will switch to this new state when the recently opened tag was eg a script-tag?

**Comment by lexborisov** [comment]
@PhiTux 

> So do I understand it right, that I will switch to this new state when the recently opened tag was eg a script-tag?

Yes, you switch the state, when you meet the opening of the tag. After the tokenizer encounters the closing of the tag, it will return to its normal state.

I did not give a complete example. Here is the true one:
```C
static lxb_html_token_t *
token_callback(lxb_html_tokenizer_t *tkz, lxb_html_token_t *token, void *ctx)
{
    /* This function will switch the state to the desired location. */
    lxb_html_tokenizer_set_state_by_tag(tkz, false, token->tag_id, LXB_NS_HTML);

    return token;
}
```

**Comment by PhiTux** [comment]
Hmm, I do not yet get it to work completely.

When the first token is passed to the callback (containing the opening script tag), and I recognize it there, then I do set the state as you told. 
That seems to work, since the following output of the second callback is completely different than before. So the state is probably set correctly. 

But: the content of this second token is all the rest inside the html-input. So it is not limited to the content in between the opening and closing script-tag. It seems like the script-state does not correctly recognize the end of the script-tag!?

Perhaps the place is wrong when/where I do set the state?

**Comment by lexborisov** [comment]
@PhiTux 

Please, show me your callback function. You set `tkz->tmp_tag_id = LXB_TAG_SCRIPT;`?
Earlier in the example, I forgot to specify it. Just use the function: 
```C
lxb_html_tokenizer_set_state_by_tag(tkz, false, token->tag_id, LXB_NS_HTML);
```

**Comment by PhiTux** [comment]
@lexborisov 
Thank you so much :D It's working now.
The `tmp_tag_id` was the important missing code. I'm using your first solution - the second one didn't work yet...
