### ISSUE TITLE
Missing API for checking if the element is void

### ISSUE THREAD

**Issue by rinpatch** [lexbor/lexbor#80]
In the process of migrating [fast_html](https://git.pleroma.social/pleroma/elixir-libraries/fast_html) from myhtml to lexbor I've noticed there is no equivalent function for [`myhtml_node_is_void_element`](https://github.com/lexborisov/myhtml/blob/master/source/myhtml/myhtml.c#L771) (or at least I haven't noticed it reading the code) . It's quite simple to implement that in the application code, but I think it will be useful to have in the library. Would a PR adding such functionality be welcome?

**Comment by lexborisov** [comment]
Hi @rinpatch 

You can use `lxb_html_tag_is_void` in `lexbor/html/tag.h`:
```C
lxb_html_tag_is_void(lxb_dom_node_tag_id(dom_node));
```

P.S.:
When you finish, please, send the link to me, I will set it in [README.md](https://github.com/lexbor/lexbor/blob/master/README.md). Or send a pool request with a link :)

**Comment by rinpatch** [comment]
Ah, thanks! I will send a PR once I am done
