### ISSUE TITLE
How is one supposed to parse fragments given tag name as a string with lexbor?

### ISSUE THREAD

**Issue by rinpatch** [lexbor/lexbor#81]
In [fast_html](https://git.pleroma.social/pleroma/elixir-libraries/fast_html) library, the client supplies the context tag name when parsing fragments as a string, then I used the following code to parse the fragment with myhtml:
```c
    myhtml_tag_id_t context_tag_id;
    const myhtml_tag_context_t * context_tag_context = myhtml_tag_static_search(context_bin_data, context_bin_size);
    if (context_tag_context == NULL) {
      // pass the error to the client
    } else {
      context_tag_id = context_tag_context->id;
    }
   // ...
   myhtml_parse_fragment(tree, MyENCODING_UTF_8, bin_data, bin_size, context_tag_id, 0);
```

With lexbor it seems like rather than passing the tag id, you should create the context tag in the document using the appropriate interface and then pass the document and the context tag to `lxb_html_document_parse_fragment`. But the question is, how do I get the appropriate interface/create an appropriate tag given the tag name as a string?

**Comment by lexborisov** [comment]
Hi @rinpatch 

Please, [see example](https://github.com/lexbor/lexbor/blob/master/examples/lexbor/html/element_create.c#L43).

Or use `lxb_dom_element_create()`.

**Comment by rinpatch** [comment]
Thanks!
