### ISSUE TITLE
convert char* to lxb_char_t*

### ISSUE THREAD

**Issue by mengyingzhou** [lexbor/lexbor#82]
Hi,
thanks for your great work.

I find that I can not convert the ``char*`` to ``lxb_char_t*`` directly. The parse result will be blank.  Is there any solution or API?

THX 
Mengying

**Comment by mengyingzhou** [comment]
oh. sorry to bother you. I just have found a solution.
I find that the  ``lxb_char_t*`` is the ``typedef unsigned char``.

```
unsigned char data[len];
memcpy( data, inputdata, sizeof(data) );
```

Thanks again for your work!
Mengying

**Comment by lexborisov** [comment]
@mengyingzhou 

Hi,

Why you not use casting? No need to copy, it's expensive.
You can casting `uint8_t *`, `char *`, `signed char *` to `lxb_char_t *`: `(lxb_char_t *) inputdata `.

```C
char *inputdata = "blah-blah-blah";
lxb_html_document_parse(doc, (lxb_char_t *) inputdata, len);
```

**Comment by mengyingzhou** [comment]
But it doesn't seem to work.
This is my not working code:
```c
const char *body = "<html lang=\"zh\" dir=\"ltr\"><head></head><body><div id=\"screen-reader-announcer\" role=\"status\" aria-live=\"polite\"></div><div id=\"one-google-end-of-body\"></div></body></html>";
lxb_char_t *data = (lxb_char_t *) body;
length = sizeof(data) - 1;  

document = lxb_html_document_create();

status = lxb_html_document_parse(document, data, length);
PRINT("\nHTML Tree:");
serialize(lxb_dom_interface_node(document));
```
The output:
```html
HTML Tree:
<html>
  <head>
  </head>
  <body>
  </body>
</html>
```

but if I use the file load method ``lexbor_fs_file_easy_read``  or initiate the data with type ``lxb_char_t``, it will work.
```c
lxb_char_t *data;
data = lexbor_fs_file_easy_read((const lxb_char_t *) "resource/index.html",&length);
// or like this
const lxb_char_t data[] = "<html lang=\"zh\" dir=\"ltr\"><head></head><body><div id=\"screen-reader-announcer\" role=\"status\" aria-live=\"polite\"></div><div id=\"one-google-end-of-body\"></div></body></html>";
```
the output would be ok
```html
HTML Tree:
<html lang="zh" dir="ltr">
  <head>
  </head>
  <body>
    <div id="screen-reader-announcer" role="status" aria-live="polite">
    </div>
    <div id="one-google-end-of-body">
    </div>
  </body>
</html>
```

maybe there are some bugs in the converting process?

**Comment by lexborisov** [comment]
@mengyingzhou 

I found bug I your code: `sizeof(data)` == 8 in 64 bit system, and 4 in 32 bit.
You try get size from pointer. Use `strlen` or
```C
const char body[] = "<html lang=\"zh\" dir=\"ltr\"><head></head><body><div id=\"screen-reader-announcer\" role=\"status\" aria-live=\"polite\"></div><div id=\"one-google-end-of-body\"></div></body></html>";
size_t length = sizeof(body) - 1;
```

**Comment by vtorri** [comment]
@lexborisov  you're wrong, data is not considered as a pointer but an array and sizeof(data) returns in that case len*sizeof(unsigned char), that is, len

**Comment by lexborisov** [comment]
@vtorri 

I do not quite understand your answer. For example:

```C
    char *lala = "bla-blah-blah";
    char bebe[] = "bla-blah-blah";

    printf("uint8_t: %lu\n", sizeof(uint8_t));
    printf("char: %lu\n", sizeof(char));
    printf("short: %lu\n", sizeof(short));
    printf("void *: %lu\n", sizeof(void *));
    printf("uint8_t *: %lu\n", sizeof(uint8_t *));
    printf("char *: %lu\n", sizeof(char *));
    printf("short *: %lu\n", sizeof(short *));

    printf("char *lala: %lu\n", sizeof(lala));
    printf("char bebe[]: %lu\n", sizeof(bebe));
```
out:
```
uint8_t: 1
char: 1
short: 2
void *: 8
uint8_t *: 8
char *: 8
short *: 8
short *lala: 8
char bebe[]: 14
```

**Comment by vtorri** [comment]
@lexborisov  I've test on Windows, with both 32 and 64 bits compilers, with that code : 

```
#include <stdio.h>

int main()
{
  unsigned char buf[4];
  printf("len: %d\n", (int)sizeof(buf));
  return 0;
}
```

both results are the same : 4, buf is not a pointer

For your code : 

the first 7 printf are normal, you display the size of the types. Note that for the 4th to 7th printf, you always display a size of a pointer, whatever the type is (sizeof(T*) is constant on the same arch, whatever T is)

the 2 last : 

printf("char *lala: %lu\n", sizeof(lala));   <---- lala is a pointer, you display the size of a pointer, like your examples above

printf("char bebe[]: %lu\n", sizeof(bebe));   <--- bebe is an array of char, set to a static string, 13 char + null char == 14

so when you say

```
I found bug I your code: sizeof(data) == 8 in 64 bit system, and 4 in 32 bit.
```

this is wrong, as data is declared as unsigned char data[len]. As an array, sizeof(data) == len*sizeof(char) == len

**Comment by lexborisov** [comment]
@vtorri 

You described exactly what I described in one line. Is this some kind of trolling? :)

@mengyingzhou example:

```C
const char *body = "<html lang=\"zh\" dir=\"ltr\"><head></head><body><div id=\"screen-reader-announcer\" role=\"status\" aria-live=\"polite\"></div><div id=\"one-google-end-of-body\"></div></body></html>";
lxb_char_t *data = (lxb_char_t *) body;
length = sizeof(data) - 1;  
```

`data` is a pointer, `sizeof(data)` == 8...

**Comment by vtorri** [comment]
@lexborisov ho, he changed data, sure, in that case, sizeof(data) is indeed wrong.

**Comment by lexborisov** [comment]
@mengyingzhou 

If the problem is resolved, please close the issue.

**Comment by mengyingzhou** [comment]
@lexborisov @vtorri 
Thank you two very much for helping me resolve the careless bug. 
I think the core mistake is that I miscalculated the ``length``.

Thanks again for your selfless help.

best
Mengying
