### ISSUE TITLE
How does one detect self closing nodes?

### ISSUE THREAD

**Issue by rinpatch** [lexbor/lexbor#83]
In myhtml there was [myhtml_node_is_close_self](https://github.com/lexborisov/myhtml/blob/22b1b0611e87599b0554c79bc49e925eb4a43c39/source/myhtml/myhtml.c#L763-L769), which allowed to determine if the element is self-closing or not. There seems to be no such function in lexbor and no way to get the token from a node. Sure for elements of HTML namespace `lxb_html_tag_is_void` is an acceptable alternative, but what about [foreign elements](https://html.spec.whatwg.org/#elements-2)?

**Comment by lexborisov** [comment]
@rinpatch 

Why can this knowledge be useful? That is, we can specify a flag for the node, but I don’t see why this might be needed.

**Comment by rinpatch** [comment]
Sorry for taking long to respond. When I filed the issue I was thinking more of keeping the same behavior myhtml had, but thinking about it more, it doesn't really make much sense to keep it
