### ISSUE TITLE
Error when using it with Visual Studio 2019 compiler.

### ISSUE THREAD

**Issue by Maratonec** [lexbor/lexbor#84]
I have run into problem. I have exact same code as in docs and i use it in c++ file. But I run into errors.

Code:
``` lxb_status_t status;
     const lxb_char_t *tag_name;
     lxb_html_document_t *document;

     static const lxb_char_t html[] = "<div>Work fine!</div>";
     size_t html_len = sizeof(html) - 1;

     document = lxb_html_document_create();
     if (document == NULL) {
         exit(EXIT_FAILURE);
     }

     status = lxb_html_document_parse(document, html, html_len);
     if (status != LXB_STATUS_OK) {
         exit(EXIT_FAILURE);
     }

     tag_name = lxb_dom_element_qualified_name(lxb_dom_interface_element(document->body), 
                                               NULL);

     printf("Element tag name: %s\n", tag_name);

     lxb_html_document_destroy(document);
```

Error
`1>core.obj : error LNK2019: Nerozpoznaný externí symbol __imp__lxb_html_document_create odkazovaný ve funkci _main
1>core.obj : error LNK2019: Nerozpoznaný externí symbol __imp__lxb_html_document_destroy odkazovaný ve funkci _main
1>core.obj : error LNK2019: Nerozpoznaný externí symbol __imp__lxb_html_document_parse odkazovaný ve funkci _main
1>core.obj : error LNK2019: Nerozpoznaný externí symbol __imp__lxb_dom_element_qualified_name odkazovaný ve funkci _main`
It means in english Unrecognized external symbol in function main. It is all in on line 1 in file core.obj.

I am not big fan of cmake and these things, so i download it from your repo and put it into folder under my project.

**Comment by vtorri** [comment]
@lexborisov should applythe PR #66 as it can lead to undef symbols on Windows. I don't know why it takes so much time

**Comment by lexborisov** [comment]
@Maratonec 

Fixed in https://github.com/lexbor/lexbor/commit/4c17bea6b9114e37c3f92dc0e896b9e5089eea9f.
