### ISSUE TITLE
error on fedora

### ISSUE THREAD

**Issue by sp00ck** [lexbor/lexbor#85]
first run
$ cmake . -DLEXBOR_BUILD_TESTS=ON -DLEXBOR_BUILD_EXAMPLES=ON -DLEXBOR_BUILD_SEPARATELY=ON

$cmake
[......]
 Building C object test/fuzzers/lexbor/html/CMakeFiles/fuzz_lexbor_html_test_fuzzers_lexbor_html_document_parse.dir/document_parse.c.o
/home/user/inne/lexbor/test/fuzzers/lexbor/html/document_parse.c: In function ‘main’:
/home/user/inne/lexbor/test/fuzzers/lexbor/html/document_parse.c:27:17: error: ‘loop’ undeclared (first use in this function)
   27 |                 loop = false;
      |                 ^~~~
/home/user/inne/lexbor/test/fuzzers/lexbor/html/document_parse.c:27:17: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [test/fuzzers/lexbor/html/CMakeFiles/fuzz_lexbor_html_test_fuzzers_lexbor_html_document_parse.dir/build.make:83: test/fuzzers/lexbor/html/CMakeFiles/fuzz_lexbor_html_test_fuzzers_lexbor_html_document_parse.dir/document_parse.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3819: test/fuzzers/lexbor/html/CMakeFiles/fuzz_lexbor_html_test_fuzzers_lexbor_html_document_parse.dir/all] Error 2
make: *** [Makefile:183: all] Error 2

**Comment by lexborisov** [comment]
@sp00ck 

Thanks for the report. Fixed in [d768ec8](https://github.com/lexbor/lexbor/commit/d768ec88c349944154f88738f1e73a36c20922aa).

**Comment by sp00ck** [comment]
Thx, all working ok!
