### ISSUE TITLE
undefined reference with added CFLAGS and LDFLAGS

### ISSUE THREAD

**Issue by mengyingzhou** [lexbor/lexbor#88]
@lexborisov 

Hi, I have met the same problem with the ``configure`` file. And I have added the CFLAGS and LDFLAGS to ``configure`` just like the way in this [link](https://unix.stackexchange.com/questions/149359/what-is-the-correct-syntax-to-add-cflags-and-ldflags-to-configure): 

```shell
./configure PKG_CONFIG_PATH=$PWD/../../openssl/build/lib/pkgconfig CFLAGS="-I$PWD/../../lexbor" LDFLAGS="-Wl,-rpath,$PWD/../../openssl/build/lib,-L$PWD/../../lexbor"
```

But it still shows the error.

the error is listed below:
``` shell
client.o: In function `(anonymous namespace)::message_complete_cb(http_parser*)':
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:442: undefined reference to `lxb_html_document_create'
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:447: undefined reference to `lxb_html_document_parse'
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:453: undefined reference to `lxb_dom_collection_create'
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:454: undefined reference to `lxb_dom_collection_init'
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:460: undefined reference to `lxb_dom_elements_by_attr_begin'
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:467: undefined reference to `lxb_dom_element_attr_by_name'
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:479: undefined reference to `lxb_html_document_destroy'
```

I use Ubuntu 18.04. 
I have tried to install the library both from Binary packages and source code. Neither doesn't work.

Thanks for your help!

Best, 
Mengying

_Originally posted by @mengyingzhou in https://github.com/lexbor/lexbor/issues/19#issuecomment-649326939_

**Comment by vtorri** [comment]
same, so add -llexbor

**Comment by vtorri** [comment]
let's start from the beginning. How didd you install lexbor (the complete cmake command) ?

**Comment by mengyingzhou** [comment]
@vtorri 

yes. the complete cmake command. 
git -> cmake -> sudo make -> sudo make install

**Comment by mengyingzhou** [comment]
I have found some interesting phenomena.

This machine is shared by my friend. He has pre-installed the lexbor by cmake tool.
He said he can compile the code without errors, but when I copy the same code from his home directory to my home directory. It doesn't work. 

We use the same code and the same command. 
Our environment setting, ``CPATH, LIBRARY_PATH, LD_LIBRARY_PATH`` are all set to Null.

**Comment by vtorri** [comment]
just cmake ? in that case, lexbor is installed in /usr/local

so i would do : 

```
CPPFLAGS=-I/usr/local/include/lexbor LDFLAGS="-L/usr/local/lib -llexbor" ./configure
```

and copying is bad ! ;-)

i'm waiting for @lexborisov  to merge a PR to ad pkg-config files, which should make usage of lexbor more friendly

**Comment by mengyingzhou** [comment]
You are so nice that you make so many efforts to make it better.

with your this command, it still can not work.
and BTW, the copied files are not the source code of lexbor. They are the source code of my own project which uses the lexbor. So, it's very confused me because we were both supposed to be correct with the same environment and the same code.

**Comment by vtorri** [comment]
be sure that lexbor header files (*.h) are in /usr/local/include/lexbor , and liblixbor.so* are in /usr/local/lib

**Comment by mengyingzhou** [comment]
i think they are.

```shell 
➜  ngtcp2-legacy git:(master) ✗ ll /usr/local/include/lexbor
total 32K
drwxr-xr-x 2 root root 4.0K Jun 25 09:31 core
drwxr-xr-x 3 root root 4.0K Jun 25 09:31 css
drwxr-xr-x 3 root root 4.0K Jun 25 09:31 dom
drwxr-xr-x 2 root root 4.0K Jun 25 09:31 encoding
drwxr-xr-x 5 root root 4.0K Jun 25 09:31 html
drwxr-xr-x 2 root root 4.0K Jun 25 09:31 ns
drwxr-xr-x 2 root root 4.0K Jun 25 09:31 tag
drwxr-xr-x 2 root root 4.0K Jun 25 09:31 utils
➜  ngtcp2-legacy git:(master) ✗ ll /usr/local/lib
total 15M
lrwxrwxrwx 1 root root    14 Jun 25 09:31 liblexbor.so -> liblexbor.so.1
lrwxrwxrwx 1 root root    18 Jun 25 09:31 liblexbor.so.1 -> liblexbor.so.1.0.0
-rw-r--r-- 1 root root  7.0M Jun 25 09:31 liblexbor.so.1.0.0
-rw-r--r-- 1 root root  7.6M Jun 25 09:30 liblexbor_static.a
drwxrwsr-x 4 root staff 4.0K Jun 24 16:37 python2.7
drwxrwsr-x 3 root staff 4.0K Feb  4 02:22 python3.
```

**Comment by vtorri** [comment]
can you paste the link command, please ?

**Comment by mengyingzhou** [comment]
sorry. this is the command

```shell
CPPFLAGS=-I/usr/local/include/lexbor LDFLAGS="-L/usr/local/lib -llexbor" ./configure PKG_CONFIG_PATH=$PWD/../../openssl/build/lib/pkgconfig LDFLAGS="-Wl,-rpath,$PWD/../../openssl/build/lib
```

**Comment by vtorri** [comment]
no, i mean the gcc command that does the link.

in your first message, you pasted

```
client.o: In function `(anonymous namespace)::message_complete_cb(http_parser*)':
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:442: undefined reference to `lxb_html_document_create'
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:447: undefined reference to `lxb_html_document_parse'
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:453: undefined reference to `lxb_dom_collection_create'
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:454: undefined reference to `lxb_dom_collection_init'
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:460: undefined reference to `lxb_dom_elements_by_attr_begin'
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:467: undefined reference to `lxb_dom_element_attr_by_name'
/home/aerberzhou/ngtcp2-legacy/examples/client.cc:479: undefined reference to `lxb_html_document_destroy'
```

i want what is just before, that is, the gcc command that does the link

**Comment by mengyingzhou** [comment]
I think i have found the mistake. I shouldn't add the ``,`` before  ``-llexbor``.

I sooooo apologized that I was taking too much of your precious time to fix my stupid mistake. Really, really sorry! 
Your patient help makes my day. Thanks very much.

**Comment by lexborisov** [comment]
@mengyingzhou hi

And I just started writing an answer :)

Thanks @vtorri for help.
