### ISSUE TITLE
Looking for a css parser and selector.

### ISSUE THREAD

**Issue by mario-132** [lexbor/lexbor#96]
Hi,

For my project I need a css parser and selector. I personally am really bad at writing parsers and don't want to spend the time learning how to do it properly just yet. I found your myCSS parser and the css parser in this project. Now I am wondering, which one is best for me to use? I ofc hope to get the parser that is most css3 compliant.(But doesn't neceserily have to be)

Which one do you reccommend me to use?

Thanks!
Edit:
I only need the css parser and selector, so having as little dependencies on other stuff I don't need would be nice.

**Comment by lexborisov** [comment]
Hi @timleijt 

I would not use MyCSS (only if in Modest). 

In the `lexbor` project, the CSS parser has been completely rewritten and its API has changed radically. But, I'm still testing it, the code has not been published. The selectors are next.
Everything to increase speed and save memory.

You can wait, though it's not clear how much, I have a very large workload now at my main job.

**Comment by timleijt** [comment]
Ok thank you.

**Comment by Dan-Do** [comment]
> Hi @timleijt
> 
> I would not use MyCSS (only if in Modest).
> 
> In the `lexbor` project, the CSS parser has been completely rewritten and its API has changed radically. But, I'm still testing it, the code has not been published. The selectors are next.
> Everything to increase speed and save memory.
> 
> You can wait, though it's not clear how much, I have a very large workload now at my main job.

I hope you're find to finish it. We love to hear from you soon.
Very nice lib by the way.
All the best.

**Comment by lexborisov** [comment]
@Dan-Do 

I finished refactoring CSS parser and ended the selectors. Testing before commit.
Thanks for using the library.

**Comment by BarryThrill** [comment]
> @Dan-Do
> 
> I finished refactoring CSS parser and ended the selectors. Testing before commit.
> Thanks for using the library.

Hi there! Im just curious about how the testing is going? 😁 looking forward!

**Comment by lexborisov** [comment]
@BarryThrill 

Hi!
A lot of work lately. Everything was stretched out. But I am already continuing to test selectors.

**Comment by BarryThrill** [comment]
Hey again! :D Just wanted to see how is the testing going? I have seen that there has been quite few testing commits so im glad to hear how its going! Excited to see how good lexbor will be!

**Comment by lexborisov** [comment]
Hi @BarryThrill 

In progress. Testing revealed a fundamental bug. I'm changing my approach.
I think that in 1 week everything will be ready.

**Comment by vtorri** [comment]
Hello

@lexborisov what is the status ?

Vincent

**Comment by Dan-Do** [comment]
It seems many members are waiting for this great feature :)

**Comment by BarryThrill** [comment]
> Hi @BarryThrill
> 
> In progress. Testing revealed a fundamental bug. I'm changing my approach.
> I think that in 1 week everything will be ready.

Hello! Hope you are alright and having it good and safe! 

Im excited to hear if there has been any progress as I and I believe other people are also looking forward for it :D Is there any hints on a beta test/release? :D Or any updates at all

**Comment by lexborisov** [comment]
@BarryThrill 

Hello! I have had a coronavirus and now I am catching up on lost time at my main job. (nginx, njs)

The selectors are complete and tested. But the code requires optimizations for which I still cannot allocate time.

Please wait.

**Comment by BarryThrill** [comment]
> @BarryThrill
> 
> Hello! I have had a coronavirus and now I am catching up on lost time at my main job. (nginx, njs)
> 
> The selectors are complete and tested. But the code requires optimizations for which I still cannot allocate time.
> 
> Please wait.

Hope you had it okey when having the covid. Myself I almost ended up in the hospital. Hope you doing great now and we all looking forward 😁

**Comment by jayflo** [comment]
@lexborisov will this include xpath selectors as well? Ref: https://github.com/lexbor/lexbor/issues/23#issuecomment-779336818

**Comment by lexborisov** [comment]
@jayflo 

No, [Selectors Level 4](https://drafts.csswg.org/selectors-4/) only.

**Comment by lexborisov** [comment]
@BarryThrill @vtorri  @mario-132 @jayflo @Dan-Do 

The first implementation of selectors is commented.
I would be glad to see performance tests, comparisons with Modest.

**Comment by mario-132** [comment]
So it is in a somewhat usable state? I would like to give it a try if so

**Comment by lexborisov** [comment]
@mario-132 

Usable condition.
There are tested, testing with a fuzzers, and so on.

Any feedback on usage will be helpful.

**Comment by mario-132** [comment]
Very nice, I'll give it a try tomorrow!

**Comment by kostya** [comment]
benchmark update here: https://github.com/kostya/myhtml#benchmark

**Comment by vtorri** [comment]
@kostya did you try to add some optimization flags, like -march and -mtune ?

**Comment by lexborisov** [comment]
@vtorri 

> @kostya did you try to add some optimization flags, like -march and -mtune ?

In real life, these optimizations (`-march=native`) are not used.

**Comment by vtorri** [comment]
anyway, i would like to see the differences :)

**Comment by kostya** [comment]
added benchmark on apple m1: https://github.com/kostya/lexbor#benchmark

**Comment by lexborisov** [comment]
Selectors and CSS Styles was added in the project.
